load(
    "@rules_xcodeproj//xcodeproj:defs.bzl",
    "top_level_target",
    "xcodeproj",
)
load("//bazel:macos_application.bzl", "appstore_macos_application", "developer_id_macos_application")
load("//bazel:xcarchive.bzl", "appstore_xcarchive")

exports_files(
    glob(["*"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "GarageApp.xcassets",
    srcs = glob(["GarageApp.xcassets/**"]),
    visibility = ["//visibility:public"],
)

developer_id_macos_application(
    name = "Garage.app",
    app = "//macapp/Sources/GarageApp:GarageApp",
    visibility = ["//visibility:public"],
)

appstore_macos_application(
    name = "GarageStore.app",
    app = "//macapp/Sources/GarageApp:GarageApp",
    visibility = ["//visibility:public"],
)

appstore_xcarchive(
    name = "GarageStore.xcarchive",
    bundle = "//macapp/Sources/GarageApp:GarageApp",
    visibility = ["//visibility:public"],
)

xcodeproj(
    name = "xcodeproj",
    project_name = "Garage",
    tags = ["manual"],
    top_level_targets = [
        top_level_target(
            "//macapp/Sources/GarageApp:GarageApp",
        ),
        top_level_target(
            "//macapp/Sources/LlamaXPCService:LlamaXPCService",
        ),
        top_level_target(
            "//macapp/Sources/GarageMCPServerService:GarageMCPServerService",
        ),
        top_level_target(
            "//macapp/Sources/GarageEmbedXPCService:GarageEmbedXPCService",
        ),
        top_level_target(
            "//macapp/Sources/GarageIngestXPCService:GarageIngestXPCService",
        ),
        top_level_target(
            "//macapp/Sources/GarageXPCService:GarageXPCService",
        ),
        top_level_target(
            "//macapp/Sources/ModelDownloadXPCService:ModelDownloadXPCService",
        ),
        top_level_target(
            "//macapp/Tests/GarageAppUnitTests:GarageAppUnitTests",
        ),
        top_level_target(
            "//macapp/Tests/GarageAppUITests:GarageAppUITests",
        ),
    ],
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageApp",
    actual = "//macapp/Sources/GarageApp:GarageApp",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageApp_lib",
    actual = "//macapp/Sources/GarageApp:GarageApp_lib",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageAppVersion",
    actual = "//macapp/Sources/GarageApp:GarageAppVersion",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageInstaller",
    actual = "//macapp/package:GarageInstaller",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageNotary",
    actual = "//macapp/package:GarageNotary",
    visibility = ["//visibility:public"],
)

alias(
    name = "install",
    actual = "//macapp/package:install",
    visibility = ["//visibility:public"],
)

alias(
    name = "postgres_output",
    actual = "//macapp/externals:postgres_output",
    visibility = ["//visibility:public"],
)

alias(
    name = "schema_output",
    actual = "//macapp/externals:schema_output",
    visibility = ["//visibility:public"],
)

alias(
    name = "garage",
    actual = "//macapp/Sources/GarageCLI:garage",
    visibility = ["//visibility:public"],
)

alias(
    name = "garage-mcp",
    actual = "//macapp/Sources/GarageMCPCLI:garage-mcp",
    visibility = ["//visibility:public"],
)

alias(
    name = "IngestClient_lib",
    actual = "//macapp/Sources/IngestClient:IngestClient_lib",
    visibility = ["//visibility:public"],
)

alias(
    name = "LlamaClient_lib",
    actual = "//macapp/Sources/LlamaClient:LlamaClient_lib",
    visibility = ["//visibility:public"],
)

alias(
    name = "ModelDownloadClient_lib",
    actual = "//macapp/Sources/ModelDownloadClient:ModelDownloadClient_lib",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageAppUnitTests",
    actual = "//macapp/Tests/GarageAppUnitTests:GarageAppUnitTests",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageAppUITests",
    actual = "//macapp/Tests/GarageAppUITests:GarageAppUITests",
    visibility = ["//visibility:public"],
)

alias(
    name = "LlamaClientTests",
    actual = "//macapp/Tests/LlamaClientTests:LlamaClientTests",
    visibility = ["//visibility:public"],
)

alias(
    name = "macapp",
    actual = ":GarageApp",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageDeveloperID.app",
    actual = ":Garage.app",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageAppStore.app",
    actual = ":GarageStore.app",
    visibility = ["//visibility:public"],
)

alias(
    name = "appstore.app",
    actual = ":GarageStore.app",
    visibility = ["//visibility:public"],
)

alias(
    name = "developer_id.app",
    actual = ":Garage.app",
    visibility = ["//visibility:public"],
)

alias(
    name = "store.app",
    actual = ":GarageStore.app",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageStore",
    actual = ":GarageStore.app",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageDeveloperID",
    actual = ":Garage.app",
    visibility = ["//visibility:public"],
)

alias(
    name = "installer",
    actual = ":GarageInstaller",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageApp_arm64",
    actual = "//macapp/package:GarageApp_arm64",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageApp_x86_64",
    actual = "//macapp/package:GarageApp_x86_64",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageInstaller_arm64",
    actual = "//macapp/package:GarageInstaller_arm64",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageInstaller_x86_64",
    actual = "//macapp/package:GarageInstaller_x86_64",
    visibility = ["//visibility:public"],
)

alias(
    name = "installer_arm64",
    actual = "//macapp/package:GarageInstaller_arm64",
    visibility = ["//visibility:public"],
)

alias(
    name = "installer_x86_64",
    actual = "//macapp/package:GarageInstaller_x86_64",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageAppNotary_arm64",
    actual = "//macapp/package:GarageAppNotary_arm64",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageAppNotary_x86_64",
    actual = "//macapp/package:GarageAppNotary_x86_64",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageInstallerNotary_arm64",
    actual = "//macapp/package:GarageInstallerNotary_arm64",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageInstallerNotary_x86_64",
    actual = "//macapp/package:GarageInstallerNotary_x86_64",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageInstallerNotary",
    actual = "//macapp/package:GarageInstallerNotary",
    visibility = ["//visibility:public"],
)

alias(
    name = "package",
    actual = "//macapp/package:package",
    visibility = ["//visibility:public"],
)

alias(
    name = "install_arm64",
    actual = "//macapp/package:install_arm64",
    visibility = ["//visibility:public"],
)

alias(
    name = "install_x86_64",
    actual = "//macapp/package:install_x86_64",
    visibility = ["//visibility:public"],
)

alias(
    name = "xcarchive",
    actual = ":GarageStore.xcarchive",
    visibility = ["//visibility:public"],
)

alias(
    name = "GarageAppStore.xcarchive",
    actual = ":GarageStore.xcarchive",
    visibility = ["//visibility:public"],
)

alias(
    name = "appstore.xcarchive",
    actual = ":GarageStore.xcarchive",
    visibility = ["//visibility:public"],
)

alias(
    name = "store.xcarchive",
    actual = ":GarageStore.xcarchive",
    visibility = ["//visibility:public"],
)
