# gazelle:exclude
load("@aspect_rules_py//py:defs.bzl", "py_library")

alias(
    name = "garage_proto",
    actual = "//proto:garage_proto",
    visibility = ["//visibility:public"],
)

alias(
    name = "garage_proto_py",
    actual = "//proto:garage_proto_py",
    visibility = ["//visibility:public"],
)

py_library(
    name = "proto",
    srcs = [
        "__init__.py",
        "garage_pb2.py",
        "garage_pb2_grpc.py",
    ],
    imports = ["../.."],
    tags = ["no-lint"],
    visibility = ["//visibility:public"],
    deps = [
        "//proto:garage_proto_py",
        "@pypi//grpcio",
        "@pypi//protobuf",
    ],
)
