# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import garage_pb2 as garage__pb2
except ImportError:
    import garage_pb2 as garage__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in garage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GarageServiceStub:
    """The GarageService is how the macOS app drives the Python pipeline: corpus
    reads for its views, every operation it would otherwise shell out to the
    `garage` CLI for (sources, models, backfill, fact distillation, schema,
    settings, MCP client registration), and the database facade the ingest and
    embed XPC workers persist through. Each RPC is a thin wrapper over the same
    garage_rag.ops function the CLI command calls.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/garage.GarageService/Ping',
                request_serializer=garage__pb2.PingRequest.SerializeToString,
                response_deserializer=garage__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/garage.GarageService/GetStatus',
                request_serializer=garage__pb2.StatusRequest.SerializeToString,
                response_deserializer=garage__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/garage.GarageService/GetVersion',
                request_serializer=garage__pb2.VersionRequest.SerializeToString,
                response_deserializer=garage__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/garage.GarageService/Search',
                request_serializer=garage__pb2.SearchRequest.SerializeToString,
                response_deserializer=garage__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/garage.GarageService/ListDocuments',
                request_serializer=garage__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=garage__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/garage.GarageService/GetDocument',
                request_serializer=garage__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=garage__pb2.GetDocumentResponse.FromString,
                _registered_method=True)
        self.ListSources = channel.unary_unary(
                '/garage.GarageService/ListSources',
                request_serializer=garage__pb2.ListSourcesRequest.SerializeToString,
                response_deserializer=garage__pb2.ListSourcesResponse.FromString,
                _registered_method=True)
        self.AddSource = channel.unary_unary(
                '/garage.GarageService/AddSource',
                request_serializer=garage__pb2.AddSourceRequest.SerializeToString,
                response_deserializer=garage__pb2.AddSourceResponse.FromString,
                _registered_method=True)
        self.RemoveSource = channel.unary_unary(
                '/garage.GarageService/RemoveSource',
                request_serializer=garage__pb2.RemoveSourceRequest.SerializeToString,
                response_deserializer=garage__pb2.RemoveSourceResponse.FromString,
                _registered_method=True)
        self.Scan = channel.unary_unary(
                '/garage.GarageService/Scan',
                request_serializer=garage__pb2.ScanRequest.SerializeToString,
                response_deserializer=garage__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.SyncSources = channel.unary_unary(
                '/garage.GarageService/SyncSources',
                request_serializer=garage__pb2.SyncSourcesRequest.SerializeToString,
                response_deserializer=garage__pb2.SyncSourcesResponse.FromString,
                _registered_method=True)
        self.ImportSourcesToConfig = channel.unary_unary(
                '/garage.GarageService/ImportSourcesToConfig',
                request_serializer=garage__pb2.ImportSourcesToConfigRequest.SerializeToString,
                response_deserializer=garage__pb2.ImportSourcesToConfigResponse.FromString,
                _registered_method=True)
        self.Reconcile = channel.unary_unary(
                '/garage.GarageService/Reconcile',
                request_serializer=garage__pb2.ReconcileRequest.SerializeToString,
                response_deserializer=garage__pb2.ReconcileResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/garage.GarageService/ListModels',
                request_serializer=garage__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=garage__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.RegisterModel = channel.unary_unary(
                '/garage.GarageService/RegisterModel',
                request_serializer=garage__pb2.RegisterModelRequest.SerializeToString,
                response_deserializer=garage__pb2.RegisterModelResponse.FromString,
                _registered_method=True)
        self.SetDefaultModel = channel.unary_unary(
                '/garage.GarageService/SetDefaultModel',
                request_serializer=garage__pb2.SetDefaultModelRequest.SerializeToString,
                response_deserializer=garage__pb2.SetDefaultModelResponse.FromString,
                _registered_method=True)
        self.DropModel = channel.unary_unary(
                '/garage.GarageService/DropModel',
                request_serializer=garage__pb2.DropModelRequest.SerializeToString,
                response_deserializer=garage__pb2.DropModelResponse.FromString,
                _registered_method=True)
        self.Backfill = channel.unary_stream(
                '/garage.GarageService/Backfill',
                request_serializer=garage__pb2.BackfillRequest.SerializeToString,
                response_deserializer=garage__pb2.BackfillStatus.FromString,
                _registered_method=True)
        self.EnrichFacts = channel.unary_stream(
                '/garage.GarageService/EnrichFacts',
                request_serializer=garage__pb2.EnrichFactsRequest.SerializeToString,
                response_deserializer=garage__pb2.EnrichFactsStatus.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/garage.GarageService/GetStats',
                request_serializer=garage__pb2.StatsRequest.SerializeToString,
                response_deserializer=garage__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.InitDb = channel.unary_unary(
                '/garage.GarageService/InitDb',
                request_serializer=garage__pb2.InitDbRequest.SerializeToString,
                response_deserializer=garage__pb2.InitDbResponse.FromString,
                _registered_method=True)
        self.GetSetting = channel.unary_unary(
                '/garage.GarageService/GetSetting',
                request_serializer=garage__pb2.GetSettingRequest.SerializeToString,
                response_deserializer=garage__pb2.GetSettingResponse.FromString,
                _registered_method=True)
        self.SetSetting = channel.unary_unary(
                '/garage.GarageService/SetSetting',
                request_serializer=garage__pb2.SetSettingRequest.SerializeToString,
                response_deserializer=garage__pb2.SetSettingResponse.FromString,
                _registered_method=True)
        self.McpInstall = channel.unary_unary(
                '/garage.GarageService/McpInstall',
                request_serializer=garage__pb2.McpInstallRequest.SerializeToString,
                response_deserializer=garage__pb2.McpInstallResponse.FromString,
                _registered_method=True)
        self.McpUninstall = channel.unary_unary(
                '/garage.GarageService/McpUninstall',
                request_serializer=garage__pb2.McpUninstallRequest.SerializeToString,
                response_deserializer=garage__pb2.McpUninstallResponse.FromString,
                _registered_method=True)
        self.McpStatus = channel.unary_unary(
                '/garage.GarageService/McpStatus',
                request_serializer=garage__pb2.McpStatusRequest.SerializeToString,
                response_deserializer=garage__pb2.McpStatusResponse.FromString,
                _registered_method=True)
        self.BeginIngestSession = channel.unary_unary(
                '/garage.GarageService/BeginIngestSession',
                request_serializer=garage__pb2.BeginIngestSessionRequest.SerializeToString,
                response_deserializer=garage__pb2.BeginIngestSessionResponse.FromString,
                _registered_method=True)
        self.PersistScan = channel.unary_unary(
                '/garage.GarageService/PersistScan',
                request_serializer=garage__pb2.PersistScanRequest.SerializeToString,
                response_deserializer=garage__pb2.PersistScanResponse.FromString,
                _registered_method=True)
        self.CheckDocumentStat = channel.unary_unary(
                '/garage.GarageService/CheckDocumentStat',
                request_serializer=garage__pb2.CheckDocumentStatRequest.SerializeToString,
                response_deserializer=garage__pb2.CheckDocumentStatResponse.FromString,
                _registered_method=True)
        self.PersistDocument = channel.unary_unary(
                '/garage.GarageService/PersistDocument',
                request_serializer=garage__pb2.PersistDocumentRequest.SerializeToString,
                response_deserializer=garage__pb2.PersistDocumentResponse.FromString,
                _registered_method=True)
        self.FinalizeIngestSession = channel.unary_unary(
                '/garage.GarageService/FinalizeIngestSession',
                request_serializer=garage__pb2.FinalizeIngestSessionRequest.SerializeToString,
                response_deserializer=garage__pb2.FinalizeIngestSessionResponse.FromString,
                _registered_method=True)
        self.GetEmbeddingBatches = channel.unary_unary(
                '/garage.GarageService/GetEmbeddingBatches',
                request_serializer=garage__pb2.GetEmbeddingBatchesRequest.SerializeToString,
                response_deserializer=garage__pb2.GetEmbeddingBatchesResponse.FromString,
                _registered_method=True)
        self.UpdateEmbeddings = channel.unary_unary(
                '/garage.GarageService/UpdateEmbeddings',
                request_serializer=garage__pb2.UpdateEmbeddingsRequest.SerializeToString,
                response_deserializer=garage__pb2.UpdateEmbeddingsResponse.FromString,
                _registered_method=True)


class GarageServiceServicer:
    """The GarageService is how the macOS app drives the Python pipeline: corpus
    reads for its views, every operation it would otherwise shell out to the
    `garage` CLI for (sources, models, backfill, fact distillation, schema,
    settings, MCP client registration), and the database facade the ingest and
    embed XPC workers persist through. Each RPC is a thin wrapper over the same
    garage_rag.ops function the CLI command calls.
    """

    def Ping(self, request, context):
        """Ping / Healthcheck
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Inspect server state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Version info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """--- Search ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """--- Documents & Chunks ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSources(self, request, context):
        """--- Sources ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncSources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportSourcesToConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reconcile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """--- Embedding Models ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Backfill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichFacts(self, request, context):
        """--- Facts ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """--- Schema, Stats & Settings ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitDb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def McpInstall(self, request, context):
        """--- MCP Client Registration ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def McpUninstall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def McpStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginIngestSession(self, request, context):
        """--- Database Facade for Ingest & Embed Workers ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PersistScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckDocumentStat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PersistDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeIngestSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbeddingBatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GarageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=garage__pb2.PingRequest.FromString,
                    response_serializer=garage__pb2.PingResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=garage__pb2.StatusRequest.FromString,
                    response_serializer=garage__pb2.StatusResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=garage__pb2.VersionRequest.FromString,
                    response_serializer=garage__pb2.VersionResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=garage__pb2.SearchRequest.FromString,
                    response_serializer=garage__pb2.SearchResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=garage__pb2.ListDocumentsRequest.FromString,
                    response_serializer=garage__pb2.ListDocumentsResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=garage__pb2.GetDocumentRequest.FromString,
                    response_serializer=garage__pb2.GetDocumentResponse.SerializeToString,
            ),
            'ListSources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSources,
                    request_deserializer=garage__pb2.ListSourcesRequest.FromString,
                    response_serializer=garage__pb2.ListSourcesResponse.SerializeToString,
            ),
            'AddSource': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSource,
                    request_deserializer=garage__pb2.AddSourceRequest.FromString,
                    response_serializer=garage__pb2.AddSourceResponse.SerializeToString,
            ),
            'RemoveSource': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSource,
                    request_deserializer=garage__pb2.RemoveSourceRequest.FromString,
                    response_serializer=garage__pb2.RemoveSourceResponse.SerializeToString,
            ),
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=garage__pb2.ScanRequest.FromString,
                    response_serializer=garage__pb2.ScanResponse.SerializeToString,
            ),
            'SyncSources': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncSources,
                    request_deserializer=garage__pb2.SyncSourcesRequest.FromString,
                    response_serializer=garage__pb2.SyncSourcesResponse.SerializeToString,
            ),
            'ImportSourcesToConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportSourcesToConfig,
                    request_deserializer=garage__pb2.ImportSourcesToConfigRequest.FromString,
                    response_serializer=garage__pb2.ImportSourcesToConfigResponse.SerializeToString,
            ),
            'Reconcile': grpc.unary_unary_rpc_method_handler(
                    servicer.Reconcile,
                    request_deserializer=garage__pb2.ReconcileRequest.FromString,
                    response_serializer=garage__pb2.ReconcileResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=garage__pb2.ListModelsRequest.FromString,
                    response_serializer=garage__pb2.ListModelsResponse.SerializeToString,
            ),
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=garage__pb2.RegisterModelRequest.FromString,
                    response_serializer=garage__pb2.RegisterModelResponse.SerializeToString,
            ),
            'SetDefaultModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultModel,
                    request_deserializer=garage__pb2.SetDefaultModelRequest.FromString,
                    response_serializer=garage__pb2.SetDefaultModelResponse.SerializeToString,
            ),
            'DropModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DropModel,
                    request_deserializer=garage__pb2.DropModelRequest.FromString,
                    response_serializer=garage__pb2.DropModelResponse.SerializeToString,
            ),
            'Backfill': grpc.unary_stream_rpc_method_handler(
                    servicer.Backfill,
                    request_deserializer=garage__pb2.BackfillRequest.FromString,
                    response_serializer=garage__pb2.BackfillStatus.SerializeToString,
            ),
            'EnrichFacts': grpc.unary_stream_rpc_method_handler(
                    servicer.EnrichFacts,
                    request_deserializer=garage__pb2.EnrichFactsRequest.FromString,
                    response_serializer=garage__pb2.EnrichFactsStatus.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=garage__pb2.StatsRequest.FromString,
                    response_serializer=garage__pb2.StatsResponse.SerializeToString,
            ),
            'InitDb': grpc.unary_unary_rpc_method_handler(
                    servicer.InitDb,
                    request_deserializer=garage__pb2.InitDbRequest.FromString,
                    response_serializer=garage__pb2.InitDbResponse.SerializeToString,
            ),
            'GetSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSetting,
                    request_deserializer=garage__pb2.GetSettingRequest.FromString,
                    response_serializer=garage__pb2.GetSettingResponse.SerializeToString,
            ),
            'SetSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSetting,
                    request_deserializer=garage__pb2.SetSettingRequest.FromString,
                    response_serializer=garage__pb2.SetSettingResponse.SerializeToString,
            ),
            'McpInstall': grpc.unary_unary_rpc_method_handler(
                    servicer.McpInstall,
                    request_deserializer=garage__pb2.McpInstallRequest.FromString,
                    response_serializer=garage__pb2.McpInstallResponse.SerializeToString,
            ),
            'McpUninstall': grpc.unary_unary_rpc_method_handler(
                    servicer.McpUninstall,
                    request_deserializer=garage__pb2.McpUninstallRequest.FromString,
                    response_serializer=garage__pb2.McpUninstallResponse.SerializeToString,
            ),
            'McpStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.McpStatus,
                    request_deserializer=garage__pb2.McpStatusRequest.FromString,
                    response_serializer=garage__pb2.McpStatusResponse.SerializeToString,
            ),
            'BeginIngestSession': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginIngestSession,
                    request_deserializer=garage__pb2.BeginIngestSessionRequest.FromString,
                    response_serializer=garage__pb2.BeginIngestSessionResponse.SerializeToString,
            ),
            'PersistScan': grpc.unary_unary_rpc_method_handler(
                    servicer.PersistScan,
                    request_deserializer=garage__pb2.PersistScanRequest.FromString,
                    response_serializer=garage__pb2.PersistScanResponse.SerializeToString,
            ),
            'CheckDocumentStat': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckDocumentStat,
                    request_deserializer=garage__pb2.CheckDocumentStatRequest.FromString,
                    response_serializer=garage__pb2.CheckDocumentStatResponse.SerializeToString,
            ),
            'PersistDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.PersistDocument,
                    request_deserializer=garage__pb2.PersistDocumentRequest.FromString,
                    response_serializer=garage__pb2.PersistDocumentResponse.SerializeToString,
            ),
            'FinalizeIngestSession': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeIngestSession,
                    request_deserializer=garage__pb2.FinalizeIngestSessionRequest.FromString,
                    response_serializer=garage__pb2.FinalizeIngestSessionResponse.SerializeToString,
            ),
            'GetEmbeddingBatches': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbeddingBatches,
                    request_deserializer=garage__pb2.GetEmbeddingBatchesRequest.FromString,
                    response_serializer=garage__pb2.GetEmbeddingBatchesResponse.SerializeToString,
            ),
            'UpdateEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEmbeddings,
                    request_deserializer=garage__pb2.UpdateEmbeddingsRequest.FromString,
                    response_serializer=garage__pb2.UpdateEmbeddingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'garage.GarageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('garage.GarageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GarageService:
    """The GarageService is how the macOS app drives the Python pipeline: corpus
    reads for its views, every operation it would otherwise shell out to the
    `garage` CLI for (sources, models, backfill, fact distillation, schema,
    settings, MCP client registration), and the database facade the ingest and
    embed XPC workers persist through. Each RPC is a thin wrapper over the same
    garage_rag.ops function the CLI command calls.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/Ping',
            garage__pb2.PingRequest.SerializeToString,
            garage__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/GetStatus',
            garage__pb2.StatusRequest.SerializeToString,
            garage__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/GetVersion',
            garage__pb2.VersionRequest.SerializeToString,
            garage__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/Search',
            garage__pb2.SearchRequest.SerializeToString,
            garage__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/ListDocuments',
            garage__pb2.ListDocumentsRequest.SerializeToString,
            garage__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/GetDocument',
            garage__pb2.GetDocumentRequest.SerializeToString,
            garage__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/ListSources',
            garage__pb2.ListSourcesRequest.SerializeToString,
            garage__pb2.ListSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/AddSource',
            garage__pb2.AddSourceRequest.SerializeToString,
            garage__pb2.AddSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/RemoveSource',
            garage__pb2.RemoveSourceRequest.SerializeToString,
            garage__pb2.RemoveSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/Scan',
            garage__pb2.ScanRequest.SerializeToString,
            garage__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/SyncSources',
            garage__pb2.SyncSourcesRequest.SerializeToString,
            garage__pb2.SyncSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportSourcesToConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/ImportSourcesToConfig',
            garage__pb2.ImportSourcesToConfigRequest.SerializeToString,
            garage__pb2.ImportSourcesToConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reconcile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/Reconcile',
            garage__pb2.ReconcileRequest.SerializeToString,
            garage__pb2.ReconcileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/ListModels',
            garage__pb2.ListModelsRequest.SerializeToString,
            garage__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/RegisterModel',
            garage__pb2.RegisterModelRequest.SerializeToString,
            garage__pb2.RegisterModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefaultModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/SetDefaultModel',
            garage__pb2.SetDefaultModelRequest.SerializeToString,
            garage__pb2.SetDefaultModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/DropModel',
            garage__pb2.DropModelRequest.SerializeToString,
            garage__pb2.DropModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Backfill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/garage.GarageService/Backfill',
            garage__pb2.BackfillRequest.SerializeToString,
            garage__pb2.BackfillStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichFacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/garage.GarageService/EnrichFacts',
            garage__pb2.EnrichFactsRequest.SerializeToString,
            garage__pb2.EnrichFactsStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/GetStats',
            garage__pb2.StatsRequest.SerializeToString,
            garage__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitDb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/InitDb',
            garage__pb2.InitDbRequest.SerializeToString,
            garage__pb2.InitDbResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/GetSetting',
            garage__pb2.GetSettingRequest.SerializeToString,
            garage__pb2.GetSettingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/SetSetting',
            garage__pb2.SetSettingRequest.SerializeToString,
            garage__pb2.SetSettingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def McpInstall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/McpInstall',
            garage__pb2.McpInstallRequest.SerializeToString,
            garage__pb2.McpInstallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def McpUninstall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/McpUninstall',
            garage__pb2.McpUninstallRequest.SerializeToString,
            garage__pb2.McpUninstallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def McpStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/McpStatus',
            garage__pb2.McpStatusRequest.SerializeToString,
            garage__pb2.McpStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginIngestSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/BeginIngestSession',
            garage__pb2.BeginIngestSessionRequest.SerializeToString,
            garage__pb2.BeginIngestSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PersistScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/PersistScan',
            garage__pb2.PersistScanRequest.SerializeToString,
            garage__pb2.PersistScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckDocumentStat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/CheckDocumentStat',
            garage__pb2.CheckDocumentStatRequest.SerializeToString,
            garage__pb2.CheckDocumentStatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PersistDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/PersistDocument',
            garage__pb2.PersistDocumentRequest.SerializeToString,
            garage__pb2.PersistDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeIngestSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/FinalizeIngestSession',
            garage__pb2.FinalizeIngestSessionRequest.SerializeToString,
            garage__pb2.FinalizeIngestSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbeddingBatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/GetEmbeddingBatches',
            garage__pb2.GetEmbeddingBatchesRequest.SerializeToString,
            garage__pb2.GetEmbeddingBatchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garage.GarageService/UpdateEmbeddings',
            garage__pb2.UpdateEmbeddingsRequest.SerializeToString,
            garage__pb2.UpdateEmbeddingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
