# gazelle:map_kind py_binary py_binary @aspect_rules_py//py:defs.bzl
# gazelle:map_kind py_library py_library @aspect_rules_py//py:defs.bzl
# gazelle:map_kind py_test py_test //tools/pytest:defs.bzl
# gazelle:python_generate_pyi_deps false
# gazelle:resolve py grpc @pypi//grpcio
# gazelle:resolve py garage_rag.proto //garage_python/src/garage_rag/proto
# gazelle:resolve py garage_rag.proto.garage_pb2 //garage_python/src/garage_rag/proto
# gazelle:resolve py garage_rag.proto.garage_pb2_grpc //garage_python/src/garage_rag/proto

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@aspect_rules_py//uv:defs.bzl", "gazelle_python_manifest")
load("//bazel:codesign.bzl", "codesign")
load("//bazel:python_site_packages.bzl", "python_site_packages")

gazelle_python_manifest(
    name = "gazelle_python_manifest",
    hub = "pypi",
    venvs = ["garage_rag"],
)

exports_files(
    [
        "pyproject.toml",
        "uv.lock",
    ],
    visibility = ["//visibility:public"],
)

python_site_packages(
    name = "site-packages-raw",
    visibility = ["//visibility:public"],
    deps = [
        "//garage_python/src:garage_rag",
    ],
)

codesign(
    name = "site-packages",
    src = ":site-packages-raw",
    out = "site-packages",
    options = [
        "runtime",
    ],
    parent_dir = "site-packages",
    sign = select({
        "//bazel:is_developer_id": "Developer ID Application: Richard Penwell (DWVXMLB45Y)",
        "//bazel:is_store": "Apple Distribution: Richard Penwell (DWVXMLB45Y)",
        "//conditions:default": "-",
    }),
    visibility = ["//visibility:public"],
)
