load("@rules_apple//apple:macos.bzl", "macos_xpc_service")
load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "GarageIngestXPCService_lib",
    srcs = glob(["**/*.swift"]),
    data = [
        "//garage_python:garage-par",
    ],
    module_name = "GarageIngestXPCService",
    visibility = ["//visibility:private"],
    deps = [
        "//ext:PythonKit",
        "//ext/python:python_3_14_framework",
    ],
)

macos_xpc_service(
    name = "GarageIngestXPCService",
    bundle_id = "me.rickmark.garage.ingest-xpc",
    bundle_name = "GarageIngestXPCService",
    codesignopts = [
        "--options=runtime",
    ],
    entitlements = select({
        "//bazel:is_store": ":GarageIngestXPCService.entitlements",
        "//conditions:default": None,
    }),
    infoplists = ["Info.plist"],
    minimum_os_version = "14.0",
    version = "//macapp:GarageAppVersion",
    visibility = ["//visibility:public"],
    deps = [
        ":GarageIngestXPCService_lib",
        "//ext/python:python_3_14_framework",
    ],
)
