"""HTTP client for the local inference servers: LM Studio, Ollama and the app's LlamaXPCService."""

from garage_rag.inference.client import (
    Backend,
    BackendKind,
    ChatResult,
    DownloadJob,
    InferenceAuthError,
    InferenceBadReply,
    InferenceClient,
    InferenceError,
    InferenceErrorBody,
    InferenceHTTPError,
    InferenceRefused,
    InferenceUnreachable,
    InferenceUnsupported,
    LMStudioModel,
    LoadedInstance,
    LoadResult,
    is_loopback_url,
    json_schema_format,
)

__all__ = [
    "Backend",
    "BackendKind",
    "ChatResult",
    "DownloadJob",
    "InferenceAuthError",
    "InferenceBadReply",
    "InferenceClient",
    "InferenceError",
    "InferenceErrorBody",
    "InferenceHTTPError",
    "InferenceRefused",
    "InferenceUnreachable",
    "InferenceUnsupported",
    "LMStudioModel",
    "LoadResult",
    "LoadedInstance",
    "is_loopback_url",
    "json_schema_format",
]
