load("@aspect_rules_py//py:defs.bzl", "py_library")

py_library(
    name = "inference",
    srcs = [
        "__init__.py",
        "client.py",
        "transport.py",
    ],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//garage_python/src/garage_rag/config",
        "//garage_python/src/garage_rag/db",
        "//garage_python/src/garage_rag/net",
    ],
)
