load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make")
load("//bazel:rpath.bzl", "install_name")

configure_make(
    name = "postgres",
    # Flags passed directly to the GNU ./configure script
    configure_options = [
        "--with-icu",
        "--without-readline",
        "--without-zlib",
        # Keep features minimal unless your system provides headers (like OpenSSL)
    ],
    copts = [
        "-Wno-error=unguarded-availability-new",
        "-Wno-unguarded-availability-new",
    ],
    env = {
        "AR": "/usr/bin/ar",
        "ARFLAGS": "crs",
    },
    lib_source = "@postgres//:postgres_source",
    out_binaries = [
        "initdb",
        "createdb",
        "pg_config",
        "psql",
        "postgres",
        "pg_isready",
        "pg_ctl",
        "pg_restore",
        "dropdb",
        "dropuser",
    ],
    out_data_dirs = [
        "share",
    ],
    out_data_files = [
        "lib/pgxs/src/makefiles/pgxs.mk",
    ],
    out_shared_libs = [
        "libpq.dylib",
        "plpgsql.dylib",
        "pg_trgm.dylib",
        "libpgtypes.dylib",
        "libpq.5.dylib",
        "libpgtypes.3.dylib",
        "libecpg.dylib",
        "pgoutput.dylib",
    ],
    out_static_libs = [
        "libecpg.a",
        "libpq.a",
        "libpgport.a",
        "libpgtypes.a",
        "libpgcommon.a",
    ],
    targets = [
        "world-bin",
        "install-world-bin",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//ext/libicu",
    ],
)

install_name(
    name = "postgres_rpath",
    dep = ":postgres",
    visibility = ["//visibility:public"],
)
