http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "postgres",
    build_file = "@//ext/postgres:postgres.BUILD.bazel",
    sha256 = "983ee554ec53dbeb9b70797bef9fcf4e67e117e7e48ca1463cc80b3ff8e8ff3f",
    strip_prefix = "postgresql-18.6",
    urls = ["https://ftp.postgresql.org/pub/source/v18.6/postgresql-18.6.tar.gz"],
)
