load("@rules_apple//apple:macos.bzl", "macos_unit_test")
load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "LlamaClientTests_lib",
    testonly = True,
    srcs = glob(["**/*.swift"]),
    module_name = "LlamaClientTests",
    visibility = ["//visibility:public"],
    deps = [
        "//macapp/Sources/LlamaClient:LlamaClient_lib",
    ],
)

macos_unit_test(
    name = "LlamaClientTests",
    bundle_id = "me.rickmark.garage-rag.LlamaClientTests",
    bundle_name = "LlamaClientTests",
    minimum_os_version = "14.0",
    visibility = ["//visibility:public"],
    deps = [
        ":LlamaClientTests_lib",
    ],
)
