load("@aspect_rules_py//py:defs.bzl", "py_library")

py_library(
    name = "embed",
    srcs = [
        "__init__.py",
        "base.py",
        "factory.py",
        "llama_xpc.py",
        "lmstudio.py",
        "ollama.py",
        "xpc.py",
    ],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//garage_python/src/garage_rag/config",
        "//garage_python/src/garage_rag/db",
        "//garage_python/src/garage_rag/proto",
        "//garage_python/src/garage_rag/xpc",
        "@pypi//ollama",
        "@pypi//openai",
        "@pypi//pgvector",
        "@pypi//sqlalchemy",
    ],
)
