load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_library")

py_binary(
    name = "garage",
    srcs = ["cli.py"],
    data = [
        "//src/data/schema:config_schema",
        "//src/data/sql:sql_schema",
    ],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//rich",
        "@pypi//sqlalchemy",
        "@pypi//typer",
    ],
)

py_library(
    name = "garage_rag",
    srcs = [
        "__init__.py",
        "cli.py",
        "config.py",
    ],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//pydantic",
        "@pypi//rich",
        "@pypi//sqlalchemy",
        "@pypi//typer",
    ],
)
