"""Configuration: one JSON file, no environment variables.

The file is **nested** because that is what is pleasant to edit; :class:`Settings`
is **flat** because that is what is pleasant to use from code. :data:`SECTIONS`
is the only thing that knows both shapes, and it drives loading, saving, and
schema generation, so the three can never disagree.

Search order, first match wins:

1. ``--config PATH`` passed explicitly
2. ``./garage.json`` -- a project-local override
3. ``~/.garage.json`` -- the default

JSON cannot carry comments, so every field's documentation lives in the generated
schema, which every config references by URL through its ``$schema`` key. Editors
then validate and describe fields inline, which is what the comments would have
been for -- and because the reference is a URL rather than a path, a config in
``$HOME`` needs no local schema copy beside it.

The schema is generated from this module (``garage config schema``) and committed
at the repository root so :data:`SCHEMA_URL` resolves. Regenerate it whenever a
setting is added, renamed, or documented; a test fails if a field is left
undescribed.

Unknown keys are an **error**, not something ignored. A silently dropped typo in a
config file is a bug you find hours later, wondering why a setting had no effect.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field, ValidationError

CONFIG_FILENAME = "garage.json"
SCHEMA_FILENAME = "garage.schema.json"
# The default lives in the home directory as a dotfile.
USER_CONFIG_FILENAME = ".garage.json"

# Published schema. Written into every config's ``$schema`` key so editors can
# resolve it without a local copy -- which matters because the config lives in
# $HOME while the schema is a build artifact of this repository.
SCHEMA_URL = (
    "https://raw.githubusercontent.com/rickmark/garage-rag/"
    "refs/heads/main/garage.schema.json"
)

# Directory names that are never worth indexing. Skipping these at the walker
# level is what keeps ~/Developer at ~18k documents instead of ~192k.
DEFAULT_EXCLUDE_DIRS: frozenset[str] = frozenset(
    {
        ".git", ".hg", ".svn",
        "node_modules", "vendor", "Pods", "Carthage",
        ".venv", "venv", "site-packages", "__pycache__",
        ".mypy_cache", ".pytest_cache", ".ruff_cache",
        "build", "dist", ".build", "DerivedData",
        ".next", ".nuxt", ".cache", ".terraform",
        ".tox", ".gradle", "target",
        # Test fixtures and golden files. Third-party corpora get checked in as
        # test data: War and Peace, the complete Shakespeare, and Tom Sawyer all
        # appear in this corpus as compression fixtures.
        "testdata", "test_data", "fixtures", "__fixtures__",
        "snapshots", "__snapshots__", "golden", "goldens",
        "buildtools", "third_party", "thirdparty", "external",
        # macOS bundles: opaque directories, not documents.
        "Contents",
    }
)

# Dependency caches identified by a path fragment rather than a single directory
# name, because the distinctive component ("mod", "registry") is too generic to
# exclude on its own.
DEPENDENCY_PATH_FRAGMENTS: tuple[str, ...] = (
    "go/pkg/mod",
    ".cargo/registry",
    ".rustup/toolchains",
    ".pub-cache",
    ".gem/",
    ".nuget/",
    ".m2/repository",
    ".cocoapods/",
    "Library/Caches",
)

# Dropbox subtrees holding applications and binary objects rather than writing.
DEFAULT_EXCLUDE_PREFIXES: tuple[str, ...] = ("Library/", "Objects/", "Software/")

# Diagnostic bundles: machine-generated by definition. One macOS sysdiagnose in
# this corpus produced ~200k chunks of log noise -- 76% of the whole index -- so
# these are matched as glob patterns against directory names and pruned before
# the walker ever descends into them.
DIAGNOSTIC_DIR_PATTERNS: tuple[str, ...] = (
    "sysdiagnose_*", "*.logarchive", "*.xcresult", "*.crash",
    "DiagnosticReports", "CrashReporter", "ioreg", "logs", "Logs",
    "spindump*", "*.dSYM", "CoreSimulator", "Diagnostics",
)

# Filenames that are machine output regardless of extension.
DIAGNOSTIC_FILE_PATTERNS: tuple[str, ...] = (
    "*.hash.txt", "*.sha.txt", "*.sha256*", "*.md5",
    "apticket*", "*.der.txt", "*.plist.txt",
    "spindump*.txt", "pmset*.txt", "taskinfo*.txt", "launchctl*.txt",
    "*_status.txt", "ps.txt", "netstat*.txt", "vm_stat*.txt",
    "system_profiler*.txt", "*.stackshot", "*.ips", "*.diag", "*.panic",
)


class SourceSpec(BaseModel):
    """A source declared in the config file.

    Declared sources are authoritative: every run re-applies them to the
    database. Sources *only* in the database are left alone -- removing a line
    from this file must never silently delete indexed documents.
    """

    model_config = {"extra": "forbid"}

    slug: str = Field(description="Short unique name, e.g. 'dropbox'.")
    root: str = Field(description="Directory or file to index. '~' is expanded.")
    kind: str = Field(
        default="filesystem",
        description="filesystem | git | sqlite | maildir | feed",
    )
    corpus_class: str = Field(
        default="document",
        alias="class",
        description="Default grouping: document | code | communication",
    )
    trust: str = Field(
        default="authored",
        description="Default trust: authored | reference | received",
    )
    include_code: bool = Field(
        default=False,
        description="Index source files as well as documents.",
    )
    allow_cloud_enrichment: bool = Field(
        default=False,
        description=(
            "Permit the cloud OCR fallback for this source. Never honoured for "
            "communication sources."
        ),
    )
    enabled: bool = Field(default=True, description="Set false to skip this source.")

    @property
    def expanded_root(self) -> Path:
        return Path(self.root).expanduser()


class Settings(BaseModel):
    """Flat view of the configuration, as the rest of the code consumes it."""

    model_config = {"extra": "forbid"}

    # ---- database -------------------------------------------------------
    database_url: str = Field(
        default="postgresql+psycopg:///rag",
        description="SQLAlchemy URL for the RAG database (psycopg3 driver).",
    )
    hnsw_ef_search: int = Field(
        default=100,
        description="HNSW probe width at query time. Higher is better recall, slower.",
    )

    # ---- identity -------------------------------------------------------
    self_name: str = Field(
        default="", description="Display name of the corpus owner."
    )
    self_identities: list[str] = Field(
        default_factory=list,
        description=(
            "Identities belonging to the owner as 'kind:value' strings, e.g. "
            "'git_email:me@example.com'. Anything authored by an identity NOT "
            "listed here is treated as reference rather than authored."
        ),
    )

    # ---- embeddings -----------------------------------------------------
    ollama_host: str = Field(
        default="http://localhost:11434",
        description="Base URL of the Ollama server that produces embeddings.",
    )
    default_embedding_model: str = Field(
        default="bge-m3",
        description=(
            "Slug of the model used when a command does not name one. Must be "
            "registered with 'garage register-model' first."
        ),
    )
    embed_batch_size: int = Field(
        default=64, description="Chunks per embedding request."
    )
    embed_max_inflight: int = Field(
        default=1,
        description=(
            "Concurrent embedding requests. Ollama serializes model execution, so "
            "more than one adds contention rather than throughput."
        ),
    )

    # ---- chunking -------------------------------------------------------
    chunk_size: int = Field(
        default=1000, description="Target characters per prose chunk."
    )
    chunk_overlap: int = Field(
        default=150,
        description=(
            "Characters repeated between adjacent prose chunks, so a sentence "
            "spanning a boundary is still retrievable."
        ),
    )
    code_chunk_size: int = Field(
        default=1200,
        description="Target characters per code chunk. Larger, to keep functions intact.",
    )
    code_chunk_overlap: int = Field(
        default=100, description="Characters repeated between adjacent code chunks."
    )
    comms_window_minutes: int = Field(
        default=30,
        description=(
            "Group consecutive messages within this many minutes into one chunk. "
            "Individual messages are too short to embed usefully."
        ),
    )
    comms_window_messages: int = Field(
        default=20,
        description="Also close a conversation window after this many messages.",
    )

    # ---- cloud placeholders ---------------------------------------------
    materialize_placeholders: bool = Field(
        default=False,
        description=(
            "Download cloud placeholder files when encountered. Reading a stub "
            "asks the provider to fetch it, so a large online-only folder can "
            "mean hundreds of gigabytes. Bounded by the limits below."
        ),
    )
    materialize_limit: int = Field(
        default=2000, description="Files materialized per run; 0 means unlimited."
    )
    materialize_max_bytes: int = Field(
        default=20 * 1024**3, description="Byte budget per run; 0 means unlimited."
    )
    materialize_timeout_seconds: float = Field(
        default=120.0,
        description=(
            "Give up on a single download that never arrives. A stalled provider "
            "cannot be cancelled, so this stops it blocking the run."
        ),
    )

    # ---- MCP server -----------------------------------------------------
    mcp_host: str = Field(
        default="127.0.0.1",
        description=(
            "Bind address. This server has no authentication and exposes the "
            "whole corpus, so a non-loopback address needs --allow-remote."
        ),
    )
    mcp_port: int = Field(default=8787, description="Port for the HTTP transport.")
    mcp_http_path: str = Field(
        default="/mcp", description="HTTP route the MCP endpoint is served on."
    )

    # ---- quality guards -------------------------------------------------
    max_chunks_per_document: int = Field(
        default=1500,
        description="Backstop so no single document can dominate the index.",
    )
    reject_machine_generated: bool = Field(
        default=True,
        description="Reject logs, dumps, and checksum manifests by content shape.",
    )

    # ---- extraction -----------------------------------------------------
    max_file_bytes: int = Field(
        default=64 * 1024 * 1024,
        description="Skip files larger than this; usually archives or disk images.",
    )
    pdf_min_chars_per_page: int = Field(
        default=32,
        description="Below this, escalate a PDF page from pypdf to pdfplumber.",
    )
    ocr_min_confidence: float = Field(
        default=60.0,
        description="Mean Tesseract word confidence below which cloud OCR is considered.",
    )
    ocr_min_chars: int = Field(
        default=16,
        description=(
            "Below this many characters an image is treated as having no text. "
            "Most images in a source tree are icons."
        ),
    )
    extract_workers: int = Field(
        default=10,
        description="Extraction worker processes. Leave headroom for Postgres and Ollama.",
    )

    # ---- cloud ----------------------------------------------------------
    enable_cloud_ocr: bool = Field(
        default=False,
        description="Allow the Claude vision fallback for unreadable images.",
    )
    cloud_ocr_model: str = Field(
        default="claude-opus-4-8",
        description="Model used for the vision OCR fallback.",
    )
    cloud_ocr_max_images: int = Field(
        default=500, description="Cap on images escalated to the cloud per run."
    )
    api_key_file: str | None = Field(
        default=None,
        description=(
            "Path to a file containing the Anthropic API key. Kept out of this "
            "file so the config itself holds no secrets."
        ),
    )

    # ---- sources --------------------------------------------------------
    sources: list[SourceSpec] = Field(
        default_factory=list,
        description=(
            "Sources to index. Declared sources are re-applied on every run; "
            "sources present only in the database are left untouched."
        ),
    )

    # Where this configuration came from. Not part of the file.
    config_path: Path | None = Field(default=None, exclude=True)

    # ---- derived --------------------------------------------------------
    def self_identity_pairs(self) -> list[tuple[str, str]]:
        """Parse ``self_identities`` into ``(kind, value)`` tuples."""
        pairs: list[tuple[str, str]] = []
        for raw in self.self_identities:
            kind, _, value = raw.partition(":")
            if value:
                pairs.append((kind.strip(), value.strip()))
        return pairs

    def read_api_key(self) -> str | None:
        """Load the Anthropic key from ``api_key_file``, if configured.

        Returns None rather than raising when unset, so the cloud path degrades
        to local-only instead of failing the whole run.
        """
        if not self.api_key_file:
            return None
        path = Path(self.api_key_file).expanduser()
        try:
            key = path.read_text(encoding="utf-8").strip()
        except OSError:
            return None
        return key or None

    def source(self, slug: str) -> SourceSpec | None:
        return next((s for s in self.sources if s.slug == slug), None)


# The nested file layout: section -> {key in file: flat field on Settings}.
# The single point of truth for both shapes.
SECTIONS: dict[str, dict[str, str]] = {
    "database": {
        "url": "database_url",
        "hnsw_ef_search": "hnsw_ef_search",
    },
    "identity": {
        "name": "self_name",
        "identities": "self_identities",
    },
    "embedding": {
        "ollama_host": "ollama_host",
        "default_model": "default_embedding_model",
        "batch_size": "embed_batch_size",
        "max_inflight": "embed_max_inflight",
    },
    "chunking": {
        "size": "chunk_size",
        "overlap": "chunk_overlap",
        "code_size": "code_chunk_size",
        "code_overlap": "code_chunk_overlap",
        "comms_window_minutes": "comms_window_minutes",
        "comms_window_messages": "comms_window_messages",
    },
    "placeholders": {
        "materialize": "materialize_placeholders",
        "limit": "materialize_limit",
        "max_bytes": "materialize_max_bytes",
        "timeout_seconds": "materialize_timeout_seconds",
    },
    "quality": {
        "max_chunks_per_document": "max_chunks_per_document",
        "reject_machine_generated": "reject_machine_generated",
    },
    "extraction": {
        "max_file_bytes": "max_file_bytes",
        "pdf_min_chars_per_page": "pdf_min_chars_per_page",
        "ocr_min_confidence": "ocr_min_confidence",
        "ocr_min_chars": "ocr_min_chars",
        "workers": "extract_workers",
    },
    "mcp": {
        "host": "mcp_host",
        "port": "mcp_port",
        "path": "mcp_http_path",
    },
    "cloud": {
        "enable_ocr": "enable_cloud_ocr",
        "model": "cloud_ocr_model",
        "max_images": "cloud_ocr_max_images",
        "api_key_file": "api_key_file",
    },
}


class ConfigError(Exception):
    """The configuration file is missing, malformed, or has unknown keys."""


def default_config_path() -> Path:
    """The default location: ``~/.garage.json``."""
    return Path.home() / USER_CONFIG_FILENAME


def repo_schema_path() -> Path:
    """Where the schema is generated for publishing.

    Committed at the repository root so that :data:`SCHEMA_URL` resolves. This is
    a build artifact, not something written next to a user's config.
    """
    return repo_root() / SCHEMA_FILENAME


def candidate_paths() -> list[Path]:
    return [Path.cwd() / CONFIG_FILENAME, default_config_path()]


def find_config_file() -> Path | None:
    """First existing config in the search order, or None."""
    return next((p for p in candidate_paths() if p.is_file()), None)


def flatten(document: dict[str, Any]) -> dict[str, Any]:
    """Nested file layout -> flat Settings kwargs.

    Raises :class:`ConfigError` on unknown sections or keys, so a typo is
    reported rather than silently having no effect.
    """
    flat: dict[str, Any] = {}
    for section, body in document.items():
        if section.startswith("$"):
            # $schema and friends are metadata for editors.
            continue
        if section == "sources":
            if not isinstance(body, list):
                raise ConfigError("'sources' must be a list")
            flat["sources"] = body
            continue
        if section not in SECTIONS:
            known = ", ".join([*SECTIONS, "sources"])
            raise ConfigError(f"unknown section {section!r}; expected one of: {known}")
        if not isinstance(body, dict):
            raise ConfigError(f"section {section!r} must be an object")
        mapping = SECTIONS[section]
        for key, value in body.items():
            field = mapping.get(key)
            if field is None:
                raise ConfigError(
                    f"unknown key {key!r} in section {section!r}; "
                    f"expected one of: {', '.join(mapping)}"
                )
            flat[field] = value
    return flat


def nest(
    settings: Settings,
    *,
    include_defaults: bool = True,
    schema_ref: str = SCHEMA_URL,
) -> dict[str, Any]:
    """Flat Settings -> nested file layout."""
    defaults = Settings()
    document: dict[str, Any] = {"$schema": schema_ref}

    for section, mapping in SECTIONS.items():
        body: dict[str, Any] = {}
        for key, field in mapping.items():
            value = getattr(settings, field)
            if not include_defaults and value == getattr(defaults, field):
                continue
            body[key] = value
        if body:
            document[section] = body

    if settings.sources:
        document["sources"] = [
            spec.model_dump(by_alias=True, exclude_defaults=not include_defaults)
            for spec in settings.sources
        ]
    return document


def load_config(path: Path | None = None, *, required: bool = False) -> Settings:
    """Load configuration from ``path``, or from the search order."""
    resolved = path.expanduser() if path is not None else find_config_file()

    if resolved is None or not resolved.is_file():
        if required or path is not None:
            searched = ", ".join(str(p) for p in ([resolved] if path else candidate_paths()))
            raise ConfigError(
                f"no config file found (looked at: {searched}); "
                "create one with 'garage config init'"
            )
        # No file at all: defaults are a usable configuration.
        return Settings()

    try:
        raw = json.loads(resolved.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ConfigError(f"{resolved} is not valid JSON: {exc}") from exc
    except OSError as exc:
        raise ConfigError(f"cannot read {resolved}: {exc}") from exc

    if not isinstance(raw, dict):
        raise ConfigError(f"{resolved} must contain a JSON object")

    try:
        settings = Settings(**flatten(raw))
    except ValidationError as exc:
        raise ConfigError(f"{resolved}: {exc}") from exc

    settings.config_path = resolved
    return settings


def save_config(settings: Settings, path: Path) -> None:
    """Write ``settings`` to ``path`` atomically.

    ``$schema`` points at the published URL rather than a neighbouring file, so a
    config in ``$HOME`` still validates in an editor with nothing else installed.
    """
    path = path.expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(nest(settings), indent=2, ensure_ascii=False) + "\n"
    temp = path.with_suffix(path.suffix + ".tmp")
    temp.write_text(payload, encoding="utf-8")
    temp.replace(path)


def json_schema() -> dict[str, Any]:
    """A JSON Schema for the nested file.

    Hand-assembled from :data:`SECTIONS` plus each field's description, because
    the file shape is nested while the model is flat. This is where the
    documentation lives, since JSON has no comments.
    """
    fields = Settings.model_fields
    properties: dict[str, Any] = {
        "$schema": {"type": "string", "description": "Path or URL to this schema."}
    }

    type_map: dict[Any, str] = {
        str: "string",
        int: "integer",
        float: "number",
        bool: "boolean",
    }

    for section, mapping in SECTIONS.items():
        section_props: dict[str, Any] = {}
        for key, name in mapping.items():
            info = fields[name]
            annotation = info.annotation
            entry: dict[str, Any] = {}
            if annotation == list[str]:
                entry["type"] = "array"
                entry["items"] = {"type": "string"}
            elif annotation in type_map:
                entry["type"] = type_map[annotation]
            elif annotation == (str | None):
                entry["type"] = ["string", "null"]
            if info.description:
                entry["description"] = info.description
            default = Settings.model_fields[name].get_default(call_default_factory=True)
            if default is not None:
                entry["default"] = default
            section_props[key] = entry
        properties[section] = {
            "type": "object",
            "additionalProperties": False,
            "properties": section_props,
        }

    source_props: dict[str, Any] = {}
    for name, info in SourceSpec.model_fields.items():
        key = info.alias or name
        entry = {}
        if info.annotation is bool:
            entry["type"] = "boolean"
        else:
            entry["type"] = "string"
        if info.description:
            entry["description"] = info.description
        source_props[key] = entry

    properties["sources"] = {
        "type": "array",
        "description": Settings.model_fields["sources"].description,
        "items": {
            "type": "object",
            "additionalProperties": False,
            "required": ["slug", "root"],
            "properties": source_props,
        },
    }

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "garage-rag configuration",
        "type": "object",
        "additionalProperties": False,
        "properties": properties,
    }


_settings: Settings | None = None


def get_settings() -> Settings:
    """Process-wide settings singleton."""
    global _settings
    if _settings is None:
        _settings = load_config()
    return _settings


def set_settings(settings: Settings) -> None:
    """Install a specific configuration. Used by the CLI's --config option."""
    global _settings
    _settings = settings


def reset_settings() -> None:
    global _settings
    _settings = None


def repo_root() -> Path:
    """Path to the installed package's project root (holds ``sql/``)."""
    return Path(__file__).resolve().parent.parent.parent


# Kept so modules importing this name keep working; the MCP server no longer
# depends on an environment variable to find its configuration.
def python_executable() -> str:
    return sys.executable
