"""Configuration, loaded from environment / .env.

Every tunable lives here so that ingest, search, and the MCP server agree on
the same values without passing them around.
"""

from __future__ import annotations

from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

# Directory names that are never worth indexing. Skipping these at the walker
# level is what keeps ~/Developer at ~18k documents instead of ~36k.
DEFAULT_EXCLUDE_DIRS: frozenset[str] = frozenset(
    {
        ".git", ".hg", ".svn",
        "node_modules", "vendor", "Pods", "Carthage",
        ".venv", "venv", "site-packages", "__pycache__",
        ".mypy_cache", ".pytest_cache", ".ruff_cache",
        "build", "dist", ".build", "DerivedData",
        ".next", ".nuxt", ".cache", ".terraform",
        ".tox", ".gradle", "target",
        # macOS bundles: opaque directories, not documents.
        "Contents",
    }
)

# Dropbox subtrees holding applications and binary objects rather than writing.
DEFAULT_EXCLUDE_PREFIXES: tuple[str, ...] = (
    "Library/",
    "Objects/",
    "Software/",
)

# Diagnostic bundles: machine-generated by definition. One macOS sysdiagnose in
# this corpus produced ~200k chunks of log noise -- 76% of the whole index -- so
# these are matched as glob patterns against directory names and pruned before
# the walker ever descends into them.
DIAGNOSTIC_DIR_PATTERNS: tuple[str, ...] = (
    "sysdiagnose_*",
    "*.logarchive",
    "*.xcresult",
    "*.crash",
    "DiagnosticReports",
    "CrashReporter",
    "ioreg",
    "logs",
    "Logs",
    "spindump*",
    "*.dSYM",
    "CoreSimulator",
    "Diagnostics",
)

# Filenames that are machine output regardless of extension.
DIAGNOSTIC_FILE_PATTERNS: tuple[str, ...] = (
    "*.hash.txt",
    "*.sha.txt",
    "*.sha256*",
    "*.md5",
    "apticket*",
    "*.der.txt",
    "*.plist.txt",
    "spindump*.txt",
    "pmset*.txt",
    "taskinfo*.txt",
    "launchctl*.txt",
    "*_status.txt",
    "ps.txt",
    "netstat*.txt",
    "vm_stat*.txt",
    "system_profiler*.txt",
    "*.stackshot",
    "*.ips",
    "*.diag",
    "*.panic",
)


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="GARAGE_",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # ---- database -------------------------------------------------------
    # psycopg3 driver: langchain-postgres is not used, so no asyncpg default.
    database_url: str = Field(
        default="postgresql+psycopg:///rag",
        description="SQLAlchemy URL for the RAG database.",
    )
    # Recall/quality knob for HNSW probes; set per session before searching.
    hnsw_ef_search: int = 100

    # ---- identity -------------------------------------------------------
    self_name: str = Field(default="", description="Display name of the corpus owner.")
    self_identities: list[str] = Field(
        default_factory=list,
        description=(
            "Identities belonging to the corpus owner, as 'kind:value' pairs, "
            "e.g. 'git_email:me@example.com'. Used to distinguish authored "
            "material from reference material."
        ),
    )

    # ---- embeddings -----------------------------------------------------
    ollama_host: str = "http://localhost:11434"
    default_embedding_model: str = "bge-m3"
    embed_batch_size: int = 64
    # Ollama serializes model execution, so client-side fan-out adds contention
    # rather than throughput. One batching producer is correct.
    embed_max_inflight: int = 1

    # ---- chunking -------------------------------------------------------
    chunk_size: int = 1000
    chunk_overlap: int = 150
    code_chunk_size: int = 1200
    code_chunk_overlap: int = 100
    # Conversation windowing: single messages embed poorly, so consecutive
    # messages in a thread are grouped.
    comms_window_minutes: int = 30
    comms_window_messages: int = 20

    # ---- cloud placeholders ---------------------------------------------
    # Reading a cloud stub asks the provider to download it. Opt-in, because a
    # naive walk over an online-only folder would otherwise turn into a
    # multi-hundred-gigabyte transfer without ever saying so.
    materialize_placeholders: bool = False
    # Files materialized per run; 0 means unlimited. A bounded default keeps the
    # first run finite and resumable -- idempotency makes re-runs cheap, so
    # repeated bounded runs converge on a full corpus.
    materialize_limit: int = 2000
    # Byte budget per run; 0 means unlimited.
    materialize_max_bytes: int = 20 * 1024**3
    # Give up on a single file that never arrives.
    materialize_timeout_seconds: float = 120.0

    # ---- quality guards -------------------------------------------------
    # Backstop against machine-generated text that path rules miss. A single
    # document producing more chunks than this is truncated and flagged rather
    # than allowed to dominate the index.
    max_chunks_per_document: int = 2500
    # Content-based machine-generated detection, applied after extraction.
    reject_machine_generated: bool = True

    # ---- extraction -----------------------------------------------------
    max_file_bytes: int = 64 * 1024 * 1024
    # Below this many characters per page, escalate pypdf -> pdfplumber.
    pdf_min_chars_per_page: int = 32
    # Mean Tesseract word confidence below this escalates to the cloud fallback
    # (when, and only when, the source permits it).
    ocr_min_confidence: float = 60.0
    ocr_min_chars: int = 16

    # ---- parallelism ----------------------------------------------------
    # 10 of 16 cores; leaves headroom for Postgres and Ollama.
    extract_workers: int = 10

    # ---- cloud fallback -------------------------------------------------
    enable_cloud_ocr: bool = False
    cloud_ocr_model: str = "claude-opus-4-8"
    cloud_ocr_max_images: int = 500

    def self_identity_pairs(self) -> list[tuple[str, str]]:
        """Parse ``self_identities`` into ``(kind, value)`` tuples."""
        pairs: list[tuple[str, str]] = []
        for raw in self_identities_iter(self.self_identities):
            kind, _, value = raw.partition(":")
            if value:
                pairs.append((kind.strip(), value.strip()))
        return pairs


def self_identities_iter(values: list[str]):
    """Yield identity strings, tolerating a single comma-joined env value."""
    for value in values:
        if "," in value:
            yield from (part for part in (p.strip() for p in value.split(",")) if part)
        else:
            yield value


_settings: Settings | None = None


def get_settings() -> Settings:
    """Process-wide settings singleton."""
    global _settings
    if _settings is None:
        _settings = Settings()
    return _settings


def repo_root() -> Path:
    """Path to the installed package's project root (holds ``sql/``)."""
    return Path(__file__).resolve().parent.parent.parent
