load("@aspect_rules_py//py:defs.bzl", "py_library")

py_library(
    name = "service",
    srcs = [
        "__init__.py",
        "client.py",
        "server.py",
    ],
    imports = ["../.."],
    visibility = ["//visibility:public"],
    deps = [
        "//garage_python/src/garage_rag/config",
        "//garage_python/src/garage_rag/db",
        "//garage_python/src/garage_rag/embed",
        "//garage_python/src/garage_rag/ingest",
        "//garage_python/src/garage_rag/ops",
        "//garage_python/src/garage_rag/proto",
        "//garage_python/src/garage_rag/search",
        "@pypi//grpcio",
        "@pypi//sqlalchemy",
    ],
)
