load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make")

configure_make(
    name = "libzlib",
    configure_command = "configure",
    configure_options = [
        "--static",
    ],
    env = {
        "AR": "/usr/bin/ar",
        "CFLAGS": "-arch arm64 -arch x86_64",
        "CXXFLAGS": "-arch arm64 -arch x86_64",
        "LDFLAGS": "-arch arm64 -arch x86_64",
    },
    lib_source = "@libzlib//:libzlib_source",
    out_static_libs = [
        "libz.a",
    ],
    visibility = ["//visibility:public"],
)
