load("@aspect_rules_py//py:defs.bzl", "py_binary")

py_binary(
    name = "pex",
    srcs = ["pex_main.py"],
    main = "pex_main.py",
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//pex:pkg",
    ],
)

filegroup(
    name = "entry_points",
    srcs = ["entry_points.txt"],
)

py_binary(
    name = "scie_tool",
    srcs = ["scie_tool.py"],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//pex:pkg",
    ],
)
