load("@rules_swift//swift:swift.bzl", "swift_binary")
load("//bazel:codesign.bzl", "codesign")

swift_binary(
    name = "garage_bin",
    srcs = ["main.swift"],
    linkopts = [
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@executable_path/../Frameworks",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@loader_path/../Frameworks",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@executable_path/../Frameworks/Python.framework",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@loader_path/../Frameworks/Python.framework",
    ],
    deps = [
        "//ext/python:python_3_13_framework",
        "//ext/pythonkit:PythonKit_swift",
    ],
)

codesign(
    name = "garage",
    src = ":garage_bin",
    entitlements = select({
        "//bazel:is_store": "//macapp/externals:GarageServer.entitlements",
        "//conditions:default": "//macapp/externals:GarageServer.entitlements",
    }),
    options = ["runtime"],
    signing_identity = select({
        "//bazel:is_adhoc": "-",
        "//bazel:is_store": "Apple Distribution: Richard Penwell (DWVXMLB45Y)",
        "//conditions:default": "Developer ID Application: Richard Penwell (DWVXMLB45Y)",
    }),
    visibility = ["//visibility:public"],
)

alias(
    name = "garage-mcp",
    actual = "//macapp/Sources/GarageMCPCLI:garage-mcp",
    visibility = ["//visibility:public"],
)
