load("@rules_apple//apple:macos.bzl", "macos_unit_test")
load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "GarageAppUnitTests_lib",
    testonly = True,
    srcs = glob(["**/*.swift"]),
    data = [
        "//docs:model_manifest",
    ],
    module_name = "GarageAppUnitTests",
    visibility = ["//visibility:public"],
    deps = [
        "//macapp/Sources/GarageApp:GarageApp_lib",
        "//macapp/Sources/GarageLauncher",
        "//macapp/Sources/GarageUpdater",
        "//macapp/Sources/IngestClient",
        "//macapp/Sources/LlamaClient",
        "//macapp/Sources/LlamaModelLoader",
        "//macapp/Sources/MCPServerClient",
        "//macapp/Sources/ModelDownloadClient",
        "//macapp/Sources/PythonXPCService",
        "//macapp/Sources/PythonXPCService:PythonXPCService_protocol",
        "//macapp/Tests/LlamaTestSupport",
    ],
)

macos_unit_test(
    name = "GarageAppUnitTests",
    timeout = "long",
    additional_linker_inputs = [
        "//ext/python:python_framework",
    ],
    bundle_id = "me.rickmark.garage-rag.GarageAppUnitTests",
    bundle_name = "GarageAppUnitTests",
    linkopts = [
        "-F$(location //ext/python:python_framework)/..",
        "-framework",
        "Python",
    ],
    minimum_os_version = "14.0",
    visibility = ["//visibility:public"],
    deps = [
        ":GarageAppUnitTests_lib",
        "//ext/python:python_framework",
    ],
)
