load("@rules_apple//apple:macos.bzl", "macos_unit_test")
load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "GarageAppUnitTests_lib",
    testonly = True,
    srcs = glob(["**/*.swift"]),
    data = [
        "//data/models:model_manifest",
    ],
    module_name = "GarageAppUnitTests",
    visibility = ["//visibility:public"],
    deps = [
        "//macapp/Sources/GarageApp:GarageApp_lib",
        "//macapp/Sources/IngestClient:IngestClient_lib",
        "//macapp/Sources/LlamaClient:LlamaClient_lib",
        "//macapp/Sources/ModelDownloadClient:ModelDownloadClient_lib",
    ],
)

macos_unit_test(
    name = "GarageAppUnitTests",
    bundle_id = "me.rickmark.garage-rag.GarageAppUnitTests",
    bundle_name = "GarageAppUnitTests",
    minimum_os_version = "14.0",
    visibility = ["//visibility:public"],
    deps = [
        ":GarageAppUnitTests_lib",
    ],
)
