load("@rules_foreign_cc//foreign_cc:defs.bzl", "make")
load("//bazel:codesign.bzl", "macho_test")

make(
    name = "pgvector",
    args = [
        "-e",
    ],
    env = {
        "PG_CONFIG": "$$EXT_BUILD_DEPS/postgres/bin/pg_config",
        "PG_CPPFLAGS": "-I$$EXT_BUILD_DEPS/postgres/include/server -I$$EXT_BUILD_DEPS/postgres/include/internal",
        "pkglibdir": "$$INSTALLDIR/lib",
        "datadir": "$$INSTALLDIR/share",
        "pkgincludedir": "$$INSTALLDIR/include",
        "CFLAGS": "-arch arm64 -g",
        "CXXFLAGS": "-arch arm64 -g",
        "LDFLAGS": "-arch arm64",
    },
    lib_source = "@pgvector//:pgvector_source",
    out_data_dirs = [
        "share",
        "lib/vector.dylib.dSYM",
    ],
    out_shared_libs = [
        "vector.dylib",
    ],
    postfix_script = "dsymutil $$INSTALLDIR/lib/vector.dylib -o $$INSTALLDIR/lib/vector.dylib.dSYM",
    visibility = ["//visibility:public"],
    deps = [
        "//ext:postgres",
    ],
)

macho_test(
    name = "pgvector_arch_test",
    src = ":pgvector",
    archs = ["arm64"],
)
