load("@rules_apple//apple:macos.bzl", "macos_xpc_service")
load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "GarageEmbedXPCService_lib",
    srcs = glob(["**/*.swift"]),
    data = [
        "//garage_python:garage-par",
    ],
    module_name = "GarageEmbedXPCService",
    visibility = ["//visibility:private"],
    deps = [
        "//ext:PythonKit",
        "//ext/python:python_3_14_framework",
    ],
)

macos_xpc_service(
    name = "GarageEmbedXPCService",
    bundle_id = "me.rickmark.garage-rag.embed-xpc",
    bundle_name = "GarageEmbedXPCService",
    codesignopts = [
        "--options=runtime",
    ],
    entitlements = ":GarageEmbedXPCService.entitlements",
    infoplists = ["Info.plist"],
    minimum_os_version = "14.0",
    version = "//macapp:GarageAppVersion",
    visibility = ["//visibility:public"],
    deps = [
        ":GarageEmbedXPCService_lib",
        "//ext/python:python_3_14_framework",
    ],
)
