load("@rules_apple//apple:macos.bzl", "macos_xpc_service")
load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "GarageEmbedXPCService_lib",
    srcs = glob(["**/*.swift"]),
    linkopts = [
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@executable_path/../Frameworks",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@loader_path/../Frameworks",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@executable_path/../Frameworks/Python.framework",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@loader_path/../Frameworks/Python.framework",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@executable_path/../../../../Frameworks",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@loader_path/../../../../Frameworks",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@executable_path/../../../../Frameworks/Python.framework",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@loader_path/../../../../Frameworks/Python.framework",
    ],
    module_name = "GarageEmbedXPCService",
    visibility = ["//visibility:private"],
    deps = [
        "//ext:PythonKit",
        "//ext/python:python_3_13_framework",
        "//macapp/Sources/IngestClient:IngestClient_lib",
        "//macapp/Sources/PythonXPCService:PythonXPCService_lib",
    ],
)

macos_xpc_service(
    name = "GarageEmbedXPCService",
    bundle_id = "me.rickmark.garage-rag.embed-xpc",
    bundle_name = "GarageEmbedXPCService",
    codesignopts = [
        "--options=runtime",
    ],
    entitlements = select({
        "//bazel:is_store": ":GarageEmbedXPCService.entitlements",
        "//conditions:default": None,
    }),
    infoplists = ["Info.plist"],
    minimum_os_version = "14.0",
    version = "//macapp/Sources/GarageApp:GarageAppVersion",
    visibility = ["//visibility:public"],
    deps = [
        ":GarageEmbedXPCService_lib",
        "//ext/python:python_3_13_framework",
    ],
)
