load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")
load("//bazel:codesign.bzl", "macho_test")

cmake(
    name = "llama_cpp",
    build_args = [
        "--",
        "-j",
    ],
    cache_entries = {
        "BUILD_SHARED_LIBS": "OFF",
        "CMAKE_BUILD_TYPE": "RelWithDebInfo",
        "GGML_BLAS": "ON",
        "GGML_BLAS_VENDOR": "Apple",
        "GGML_METAL": "ON",
        "GGML_METAL_EMBED_LIBRARY": "ON",
        "LLAMA_BUILD_APP": "OFF",
        "LLAMA_BUILD_COMMON": "OFF",
        "LLAMA_BUILD_EXAMPLES": "OFF",
        "LLAMA_BUILD_SERVER": "OFF",
        "LLAMA_BUILD_TESTS": "OFF",
        "LLAMA_BUILD_TOOLS": "OFF",
        "LLAMA_CURL": "OFF",
    },
    env = {
        "AR": "/usr/bin/ar",
        "CFLAGS": "-g",
        "CXXFLAGS": "-g",
    },
    lib_source = "@llama_cpp_framework//:llama_cpp_source",
    out_static_libs = [
        "libllama.a",
        "libggml.a",
        "libggml-base.a",
        "libggml-cpu.a",
        "libggml-blas.a",
        "libggml-metal.a",
    ],
    visibility = ["//visibility:public"],
)

macho_test(
    name = "llama_cpp_arch_test",
    src = ":llama_cpp",
    archs = [
        "arm64",
        "x86_64",
    ],
)
