load("@rules_apple//apple:macos.bzl", "macos_xpc_service")
load("@rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "GarageMCPServerService_lib",
    srcs = glob(["**/*.swift"]),
    linkopts = [
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@executable_path/../Frameworks",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@loader_path/../Frameworks",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@executable_path/../Frameworks/Python.framework",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@loader_path/../Frameworks/Python.framework",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@executable_path/../../../../Frameworks",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@loader_path/../../../../Frameworks",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@executable_path/../../../../Frameworks/Python.framework",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@loader_path/../../../../Frameworks/Python.framework",
    ],
    module_name = "GarageMCPServerService",
    visibility = ["//visibility:private"],
    deps = [
        "//ext:PythonKit",
        "//ext/python:python_3_13_framework",
    ],
)

macos_xpc_service(
    name = "GarageMCPServerService",
    bundle_id = "me.rickmark.garage-rag.mcp-server-xpc",
    bundle_name = "GarageMCPServerService",
    codesignopts = [
        "--options=runtime",
    ],
    entitlements = ":GarageMCPServerService.entitlements",
    infoplists = ["Info.plist"],
    minimum_os_version = "14.0",
    version = "//macapp:GarageAppVersion",
    visibility = ["//visibility:public"],
    deps = [
        ":GarageMCPServerService_lib",
        "//ext/python:python_3_13_framework",
    ],
)
