alias(
    name = "postgres",
    actual = "//ext/postgres:postgres",
    visibility = ["//visibility:public"],
)

alias(
    name = "pgvector",
    actual = "//ext/pgvector:pgvector",
    visibility = ["//visibility:public"],
)

alias(
    name = "libicu",
    actual = "//ext/libicu:libicu",
    visibility = ["//visibility:public"],
)

alias(
    name = "libreadline",
    actual = "//ext/libreadline:libreadline",
    visibility = ["//visibility:public"],
)

alias(
    name = "libzlib",
    actual = "//ext/libzlib:libzlib",
    visibility = ["//visibility:public"],
)

alias(
    name = "python",
    actual = "//ext/python:python_3_13",
    visibility = ["//visibility:public"],
)
