load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make")

configure_make(
    name = "python_3_14",
    args = [
        "-e",
    ],
    configure_in_place = True,
    configure_options = [
        "--enable-framework=$$INSTALLDIR$$/Frameworks",
        "--without-ensurepip",
        "--with-static-libpython",
        "--with-universal-archs",
    ],
    copts = [
        "-U__DATE__",
        "-U__TIME__",
        "-U__TIMESTAMP__",
    ],
    env = {
        "AR": "/usr/bin/ar",
        "ARFLAGS": "crs",
        "PYTHONAPPSDIR": "$$INSTALLDIR$$/Applications",
    },
    lib_source = "@python_3_14_framework//:python_source",
    out_binaries = [
        "python3",
        "python3-config",
    ],
    out_static_libs = [
        "libpython3.14.a",
    ],
    visibility = ["//visibility:public"],
)

alias(
    name = "python_3_14_framework",
    actual = ":python_3_14",
    visibility = ["//visibility:public"],
)
