load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make")

configure_make(
    name = "libicu",
    configure_command = "source/configure",
    configure_options = [
        "--disable-samples",
        "--disable-tests",
        "--enable-static",
        "--disable-shared",
    ],
    env = {
        "AR": "/usr/bin/ar",
        "CFLAGS": "-arch arm64 -arch x86_64",
        "CXXFLAGS": "-arch arm64 -arch x86_64",
        "LDFLAGS": "-arch arm64 -arch x86_64",
    },
    lib_source = "@libicu//:libicu_source",
    out_static_libs = [
        "libicui18n.a",
        "libicuuc.a",
        "libicudata.a",
        "libicuio.a",
        "libicutu.a",
    ],
    visibility = ["//visibility:public"],
)
