"""Configuration: one JSON file with a database URL environment override.

The file is **nested** because that is what is pleasant to edit; :class:`Settings`
is **flat** because that is what is pleasant to use from code. :data:`SECTIONS`
is the only thing that knows both shapes, and it drives loading, saving, and
schema generation, so the three can never disagree.

Search order, first match wins:

1. ``--config PATH`` passed explicitly
2. ``./garage.json`` -- a project-local override
3. ``~/.garage.json`` -- the default

JSON cannot carry comments, so every field's documentation lives in the generated
schema, which every config references by URL through its ``$schema`` key. Editors
then validate and describe fields inline, which is what the comments would have
been for -- and because the reference is a URL rather than a path, a config in
``$HOME`` needs no local schema copy beside it.

The schema is generated from this module (``garage config schema --publish``) and
committed under ``docs/.data/``, which the website serves, so :data:`SCHEMA_URL`
resolves. Regenerate it whenever a setting is added, renamed, or documented; a
test fails if a field is left undescribed.

Unknown keys are an **error**, not something ignored. A silently dropped typo in a
config file is a bug you find hours later, wondering why a setting had no effect.
The one exception is :data:`RETIRED_KEYS`: settings that used to exist and were
removed. Those are skipped with a warning so an older file still loads.
"""

from __future__ import annotations

import ipaddress
import json
import logging
import os
from pathlib import Path
from typing import Any, Literal, get_args, get_origin
from urllib.parse import urlsplit

from pydantic import BaseModel, Field, ValidationError, field_validator, model_validator

log = logging.getLogger(__name__)

CONFIG_FILENAME = "garage.json"
SCHEMA_FILENAME = "garage.schema.json"
# The default lives in the home directory as a dotfile.
USER_CONFIG_FILENAME = ".garage.json"

# Published schema. Written into every config's ``$schema`` key so editors can
# resolve it without a local copy -- which matters because the config lives in
# $HOME while the schema is a build artifact of this repository.
SITE_URL = "https://garagerag.app"
# Files the site serves from docs/.data/ in the repository.
SITE_DATA_DIR = ".data"
SCHEMA_URL = f"{SITE_URL}/{SITE_DATA_DIR}/{SCHEMA_FILENAME}"

# Directory names that are never worth indexing. Skipping these at the walker
# level is what keeps ~/Developer at ~18k documents instead of ~192k.
DEFAULT_EXCLUDE_DIRS: frozenset[str] = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        "node_modules",
        "vendor",
        "Pods",
        "Carthage",
        ".venv",
        "venv",
        "site-packages",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        "build",
        "dist",
        ".build",
        "DerivedData",
        ".next",
        ".nuxt",
        ".cache",
        ".terraform",
        ".tox",
        ".gradle",
        "target",
        # Test fixtures and golden files. Third-party corpora get checked in as
        # test data: War and Peace, the complete Shakespeare, and Tom Sawyer all
        # appear in this corpus as compression fixtures.
        "testdata",
        "test_data",
        "fixtures",
        "__fixtures__",
        "snapshots",
        "__snapshots__",
        "golden",
        "goldens",
        "buildtools",
        "third_party",
        "thirdparty",
        "external",
        # macOS bundles: opaque directories, not documents.
        "Contents",
    }
)

# Dependency caches identified by a path fragment rather than a single directory
# name, because the distinctive component ("mod", "registry") is too generic to
# exclude on its own.
DEPENDENCY_PATH_FRAGMENTS: tuple[str, ...] = (
    "go/pkg/mod",
    ".cargo/registry",
    ".rustup/toolchains",
    ".pub-cache",
    ".gem/",
    ".nuget/",
    ".m2/repository",
    ".cocoapods/",
    "Library/Caches",
)

# Diagnostic bundles: machine-generated by definition. One macOS sysdiagnose in
# this corpus produced ~200k chunks of log noise -- 76% of the whole index -- so
# these are matched as glob patterns against directory names and pruned before
# the walker ever descends into them.
DIAGNOSTIC_DIR_PATTERNS: tuple[str, ...] = (
    "sysdiagnose_*",
    "*.logarchive",
    "*.xcresult",
    "*.crash",
    "DiagnosticReports",
    "CrashReporter",
    "ioreg",
    "logs",
    "Logs",
    "spindump*",
    "*.dSYM",
    "CoreSimulator",
    "Diagnostics",
)

# Filenames that are machine output regardless of extension.
DIAGNOSTIC_FILE_PATTERNS: tuple[str, ...] = (
    "*.hash.txt",
    "*.sha.txt",
    "*.sha256*",
    "*.md5",
    "apticket*",
    "*.der.txt",
    "*.plist.txt",
    "spindump*.txt",
    "pmset*.txt",
    "taskinfo*.txt",
    "launchctl*.txt",
    "*_status.txt",
    "ps.txt",
    "netstat*.txt",
    "vm_stat*.txt",
    "system_profiler*.txt",
    "*.stackshot",
    "*.ips",
    "*.diag",
    "*.panic",
)


def is_loopback_url(url: str) -> bool:
    """Whether ``url`` points at this machine. A bare ``host:port`` counts as a URL.

    ``localhost`` or a literal loopback address (``127.0.0.0/8``, ``::1``). Any
    other name is refused even if it resolves to loopback today: a DNS answer can
    change, and a name like ``127.example.com`` is not an address.
    """
    if "://" not in url:
        url = f"http://{url}"
    try:
        host = (urlsplit(url).hostname or "").lower().rstrip(".")
    except ValueError:
        return False
    if host == "localhost":
        return True
    try:
        return ipaddress.ip_address(host).is_loopback
    except ValueError:
        return False


class SourceSpec(BaseModel):
    """A source declared in the config file.

    Declared sources are authoritative: every run re-applies them to the
    database. Sources *only* in the database are left alone -- removing a line
    from this file must never silently delete indexed documents.
    """

    model_config = {"extra": "forbid"}

    slug: str = Field(description="Short unique name, e.g. 'dropbox'.")
    root: str = Field(description="Directory or file to index. '~' is expanded.")
    kind: str = Field(
        default="filesystem",
        description="filesystem | git | sqlite | maildir | feed",
    )
    corpus_class: str = Field(
        default="document",
        alias="class",
        description="Default grouping: document | code | communication",
    )
    trust: str = Field(
        default="authored",
        description="Default trust: authored | reference | received",
    )
    include_code: bool = Field(
        default=False,
        description="Index source files as well as documents.",
    )
    enabled: bool = Field(default=True, description="Set false to skip this source.")

    @model_validator(mode="before")
    @classmethod
    def _drop_retired_keys(cls, data: Any) -> Any:
        if isinstance(data, dict):
            retired = RETIRED_KEYS["sources"] & data.keys()
            for key in sorted(retired):
                log.warning("config: sources[].%s is no longer a setting and was ignored; remove it", key)
            data = {k: v for k, v in data.items() if k not in retired}
        return data

    @property
    def expanded_root(self) -> Path:
        return Path(self.root).expanduser()


def ensure_psycopg_database_url(url: str) -> str:
    """Ensure a PostgreSQL database URL is in the form postgresql+psycopg://."""
    if not url or not url.strip():
        return url
    trimmed = url.strip()
    if trimmed.startswith("postgresql+psycopg://"):
        return trimmed
    if trimmed.startswith("postgresql://"):
        return "postgresql+psycopg://" + trimmed[len("postgresql://") :]
    if trimmed.startswith("postgres://"):
        return "postgresql+psycopg://" + trimmed[len("postgres://") :]
    if "://" in trimmed:
        scheme, rest = trimmed.split("://", 1)
        if scheme.startswith("postgres") or scheme.startswith("postgresql"):
            return f"postgresql+psycopg://{rest}"
    return trimmed


class Settings(BaseModel):
    """Flat view of the configuration, as the rest of the code consumes it."""

    model_config = {"extra": "forbid"}

    # ---- database -------------------------------------------------------
    database_url: str = Field(
        default="postgresql+psycopg:///rag",
        description="SQLAlchemy URL for the RAG database (psycopg3 driver).",
    )

    @field_validator("database_url", mode="before")
    @classmethod
    def _validate_database_url(cls, v: Any) -> Any:
        if isinstance(v, str):
            return ensure_psycopg_database_url(v)
        return v

    hnsw_ef_search: int = Field(
        default=100,
        description="HNSW probe width at query time. Higher is better recall, slower.",
    )

    # ---- identity -------------------------------------------------------
    self_name: str = Field(default="", description="Display name of the corpus owner.")
    self_identities: list[str] = Field(
        default_factory=list,
        description=(
            "Identities belonging to the owner as 'kind:value' strings, e.g. "
            "'git_email:me@example.com'. Anything authored by an identity NOT "
            "listed here is treated as reference rather than authored."
        ),
    )

    # ---- embeddings -----------------------------------------------------
    ollama_host: str = Field(
        default="http://localhost:11434",
        description=(
            "Base URL of the Ollama server for embeddings, fact distillation and answers. May be another "
            "machine; communications are only ever sent to a loopback host."
        ),
    )
    lmstudio_host: str = Field(
        default="http://localhost:1234/v1",
        description=(
            "Base URL of the LM Studio OpenAI-compatible API (include /v1); embeddings, fact "
            "distillation, answers, and model management under /api/v1. May be another machine; "
            "communications are only ever sent to a loopback host."
        ),
    )
    llama_host: str = Field(
        default="http://127.0.0.1:8790",
        description=("Base URL of the llama.cpp HTTP API served by the app's LlamaXPCService (loopback only)."),
    )

    @field_validator("llama_host")
    @classmethod
    def _validate_llama_host(cls, v: str) -> str:
        # The app's own LlamaXPCService only ever listens on loopback.
        if not is_loopback_url(v):
            raise ValueError(f"embedding.llama_host must be a loopback URL (localhost, 127.0.0.1 or ::1); got {v!r}")
        return v

    lmstudio_api_token_file: str | None = Field(
        default=None,
        description=(
            "Path to an LM Studio API token for an authenticated server. The token itself "
            "is kept outside this configuration file; GARAGE_LMSTUDIO_API_TOKEN overrides it."
        ),
    )
    default_embedding_model: str = Field(
        default="bge-m3",
        description=(
            "Slug of the model used when a command does not name one. Must be "
            "registered with 'garage register-model' first."
        ),
    )
    embed_batch_size: int = Field(default=64, description="Chunks per embedding request.")

    # ---- chunking -------------------------------------------------------
    chunk_size: int = Field(default=1000, description="Target characters per prose chunk.")
    chunk_overlap: int = Field(
        default=150,
        description=(
            "Characters repeated between adjacent prose chunks, so a sentence spanning a boundary is still retrievable."
        ),
    )
    code_chunk_size: int = Field(
        default=1200,
        description="Target characters per code chunk. Larger, to keep functions intact.",
    )
    code_chunk_overlap: int = Field(default=100, description="Characters repeated between adjacent code chunks.")

    # ---- cloud placeholders ---------------------------------------------
    materialize_placeholders: bool = Field(
        default=False,
        description=(
            "Download cloud placeholder files when encountered. Reading a stub "
            "asks the provider to fetch it, so a large online-only folder can "
            "mean hundreds of gigabytes. Bounded by the limits below."
        ),
    )
    materialize_limit: int = Field(default=2000, description="Files materialized per run; 0 means unlimited.")
    materialize_max_bytes: int = Field(default=20 * 1024**3, description="Byte budget per run; 0 means unlimited.")
    materialize_timeout_seconds: float = Field(
        default=120.0,
        description=(
            "Give up on a single download that never arrives. A stalled provider "
            "cannot be cancelled, so this stops it blocking the run."
        ),
    )

    # ---- MCP server -----------------------------------------------------
    mcp_host: str = Field(
        default="127.0.0.1",
        description=(
            "Bind address. This server has no authentication and exposes the "
            "whole corpus, so a non-loopback address needs --allow-remote."
        ),
    )
    mcp_port: int = Field(default=8787, description="Port for the HTTP transport.")
    mcp_http_path: str = Field(default="/mcp", description="HTTP route the MCP endpoint is served on.")

    # ---- quality guards -------------------------------------------------
    max_chunks_per_document: int = Field(
        default=1500,
        description="Backstop so no single document can dominate the index.",
    )
    reject_machine_generated: bool = Field(
        default=True,
        description="Reject logs, dumps, and checksum manifests by content shape.",
    )

    # ---- extraction -----------------------------------------------------
    max_file_bytes: int = Field(
        default=64 * 1024 * 1024,
        description="Skip files larger than this; usually archives or disk images.",
    )
    pdf_min_chars_per_page: int = Field(
        default=32,
        description="Below this, escalate a PDF page from pypdf to pdfplumber.",
    )
    ocr_min_chars: int = Field(
        default=16,
        description=(
            "Below this many characters an image is treated as having no text. Most images in a source tree are icons."
        ),
    )

    # ---- facts / local generation ---------------------------------------
    fact_model: str = Field(
        default="gemma2-2b",
        description=(
            "Slug or alias of the local model used for fact distillation "
            "('garage enrich-facts') and for the rag_ask / rag_generate MCP tools. "
            "For llama_xpc this is the alias the app loaded the model under (the "
            "'fact_distil' preset slug); for ollama it is the Ollama model name; for "
            "lmstudio it is the LM Studio model key (e.g. 'google/gemma-3-4b')."
        ),
    )
    fact_provider: Literal["llama_xpc", "ollama", "lmstudio"] = Field(
        default="llama_xpc",
        description=(
            "Which inference server runs fact distillation and rag_ask: 'llama_xpc' is the "
            "app's LlamaXPCService (llama.cpp on embedding.llama_host, loopback only); "
            "'ollama' is the Ollama server on embedding.ollama_host; 'lmstudio' is the "
            "LM Studio server on embedding.lmstudio_host, which loads the model on first "
            "use. Communications are only ever sent to a loopback host."
        ),
    )

    # ---- sources --------------------------------------------------------
    sources: list[SourceSpec] = Field(
        default_factory=list,
        description=(
            "Sources to index. Declared sources are re-applied on every run; "
            "sources present only in the database are left untouched."
        ),
    )

    # Where this configuration came from. Not part of the file.
    config_path: Path | None = Field(default=None, exclude=True)

    # ---- derived --------------------------------------------------------
    def self_identity_pairs(self) -> list[tuple[str, str]]:
        """Parse ``self_identities`` into ``(kind, value)`` tuples."""
        pairs: list[tuple[str, str]] = []
        for raw in self.self_identities:
            kind, _, value = raw.partition(":")
            if value:
                pairs.append((kind.strip(), value.strip()))
        return pairs

    def read_lmstudio_api_token(self) -> str | None:
        """Load the LM Studio API token without placing it in the configuration."""
        environment_token = os.environ.get("GARAGE_LMSTUDIO_API_TOKEN")
        if environment_token is not None:
            token = environment_token.strip()
            if not token:
                raise ConfigError("GARAGE_LMSTUDIO_API_TOKEN must not be empty")
            return token
        if not self.lmstudio_api_token_file:
            return None
        path = Path(self.lmstudio_api_token_file).expanduser()
        try:
            token = path.read_text(encoding="utf-8").strip()
        except OSError as exc:
            raise ConfigError(f"cannot read LM Studio API token file {path}: {exc}") from exc
        if not token:
            raise ConfigError(f"LM Studio API token file {path} is empty")
        return token


# The nested file layout: section -> {key in file: flat field on Settings}.
# The single point of truth for both shapes.
SECTIONS: dict[str, dict[str, str]] = {
    "database": {
        "url": "database_url",
        "hnsw_ef_search": "hnsw_ef_search",
    },
    "identity": {
        "name": "self_name",
        "identities": "self_identities",
    },
    "embedding": {
        "ollama_host": "ollama_host",
        "lmstudio_host": "lmstudio_host",
        "llama_host": "llama_host",
        "lmstudio_api_token_file": "lmstudio_api_token_file",
        "default_model": "default_embedding_model",
        "batch_size": "embed_batch_size",
    },
    "chunking": {
        "size": "chunk_size",
        "overlap": "chunk_overlap",
        "code_size": "code_chunk_size",
        "code_overlap": "code_chunk_overlap",
    },
    "placeholders": {
        "materialize": "materialize_placeholders",
        "limit": "materialize_limit",
        "max_bytes": "materialize_max_bytes",
        "timeout_seconds": "materialize_timeout_seconds",
    },
    "quality": {
        "max_chunks_per_document": "max_chunks_per_document",
        "reject_machine_generated": "reject_machine_generated",
    },
    "extraction": {
        "max_file_bytes": "max_file_bytes",
        "pdf_min_chars_per_page": "pdf_min_chars_per_page",
        "ocr_min_chars": "ocr_min_chars",
    },
    "mcp": {
        "host": "mcp_host",
        "port": "mcp_port",
        "path": "mcp_http_path",
    },
    "facts": {
        "model": "fact_model",
        "provider": "fact_provider",
    },
}

# Keys that older configs may still carry: settings that were removed, either
# because no code path read them or because the feature behind them is gone.
# They are ignored with a warning rather than rejected, since a file written by
# an earlier release must keep loading. Section -> keys; a section listed here
# but absent from SECTIONS is retired whole, and "sources" covers the keys of
# each entry in the sources list.
RETIRED_KEYS: dict[str, frozenset[str]] = {
    "embedding": frozenset({"max_inflight"}),
    "chunking": frozenset({"comms_window_minutes", "comms_window_messages"}),
    # ocr_min_confidence decided when to escalate to the Claude OCR fallback,
    # which was removed along with the rest of the cloud section.
    "extraction": frozenset({"workers", "ocr_min_confidence"}),
    "cloud": frozenset({"enable_ocr", "model", "api_key_file", "max_images"}),
    "sources": frozenset({"allow_cloud_enrichment"}),
}


class ConfigError(Exception):
    """The configuration file is missing, malformed, or has unknown keys."""


def default_config_path() -> Path:
    """The default location: ``~/.garage.json``."""
    return Path.home() / USER_CONFIG_FILENAME


def repo_schema_path() -> Path:
    """Where the schema is generated for publishing.

    Committed under ``docs/.data``, which the website serves, so :data:`SCHEMA_URL`
    resolves. This is a build artifact, not something written next to a user's
    config.
    """
    return repo_root() / "docs" / SITE_DATA_DIR / SCHEMA_FILENAME


def candidate_paths() -> list[Path]:
    return [Path.cwd() / CONFIG_FILENAME, default_config_path()]


def find_config_file() -> Path | None:
    """First existing config in the search order, or None."""
    return next((p for p in candidate_paths() if p.is_file()), None)


def flatten(document: dict[str, Any]) -> dict[str, Any]:
    """Nested file layout -> flat Settings kwargs.

    Raises :class:`ConfigError` on unknown sections or keys, so a typo is
    reported rather than silently having no effect.
    """
    flat: dict[str, Any] = {}
    for section, body in document.items():
        if section.startswith("$"):
            # $schema and friends are metadata for editors.
            continue
        if section == "sources":
            if not isinstance(body, list):
                raise ConfigError("'sources' must be a list")
            flat["sources"] = body
            continue
        if section not in SECTIONS and section not in RETIRED_KEYS:
            known = ", ".join([*SECTIONS, "sources"])
            raise ConfigError(f"unknown section {section!r}; expected one of: {known}")
        if not isinstance(body, dict):
            raise ConfigError(f"section {section!r} must be an object")
        mapping = SECTIONS.get(section, {})
        for key, value in body.items():
            field = mapping.get(key)
            if field is None and key in RETIRED_KEYS.get(section, frozenset()):
                log.warning("config: %s.%s is no longer a setting and was ignored; remove it", section, key)
                continue
            if field is None:
                raise ConfigError(f"unknown key {key!r} in section {section!r}; expected one of: {', '.join(mapping)}")
            flat[field] = value
    return flat


def nest(
    settings: Settings,
    *,
    include_defaults: bool = True,
    schema_ref: str = SCHEMA_URL,
) -> dict[str, Any]:
    """Flat Settings -> nested file layout."""
    defaults = Settings()
    document: dict[str, Any] = {"$schema": schema_ref}

    for section, mapping in SECTIONS.items():
        body: dict[str, Any] = {}
        for key, field in mapping.items():
            value = getattr(settings, field)
            if not include_defaults and value == getattr(defaults, field):
                continue
            body[key] = value
        if body:
            document[section] = body

    if settings.sources:
        document["sources"] = [
            spec.model_dump(by_alias=True, exclude_defaults=not include_defaults) for spec in settings.sources
        ]
    return document


def load_config(path: Path | None = None) -> Settings:
    """Load configuration from ``path``, or from the search order.

    An explicit ``path`` must exist; with none given, no file at all means the
    defaults.
    """
    resolved = path.expanduser() if path is not None else find_config_file()

    if resolved is None or not resolved.is_file():
        if path is not None:
            searched = ", ".join(str(p) for p in ([resolved] if path else candidate_paths()))
            raise ConfigError(f"no config file found (looked at: {searched}); create one with 'garage config init'")
        # No file at all: defaults are a usable configuration.
        return _apply_database_url_environment(Settings())

    try:
        raw = json.loads(resolved.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ConfigError(f"{resolved} is not valid JSON: {exc}") from exc
    except OSError as exc:
        raise ConfigError(f"cannot read {resolved}: {exc}") from exc

    if not isinstance(raw, dict):
        raise ConfigError(f"{resolved} must contain a JSON object")

    try:
        settings = Settings(**flatten(raw))
    except ValidationError as exc:
        raise ConfigError(f"{resolved}: {exc}") from exc

    settings.config_path = resolved
    return _apply_database_url_environment(settings)


def _apply_database_url_environment(settings: Settings) -> Settings:
    """Apply the app-managed database credential without persisting it in JSON."""
    database_url = os.environ.get("GARAGE_DATABASE_URL")
    if database_url is None:
        return settings
    if not database_url.strip():
        raise ConfigError("GARAGE_DATABASE_URL must not be empty")
    settings.database_url = ensure_psycopg_database_url(database_url)
    return settings


def save_config(settings: Settings, path: Path) -> None:
    """Write ``settings`` to ``path`` atomically.

    ``$schema`` points at the published URL rather than a neighbouring file, so a
    config in ``$HOME`` still validates in an editor with nothing else installed.
    """
    path = path.expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(nest(settings), indent=2, ensure_ascii=False) + "\n"
    temp = path.with_suffix(path.suffix + ".tmp")
    temp.write_text(payload, encoding="utf-8")
    temp.replace(path)


def json_schema() -> dict[str, Any]:
    """A JSON Schema for the nested file.

    Hand-assembled from :data:`SECTIONS` plus each field's description, because
    the file shape is nested while the model is flat. This is where the
    documentation lives, since JSON has no comments.
    """
    fields = Settings.model_fields
    properties: dict[str, Any] = {"$schema": {"type": "string", "description": "Path or URL to this schema."}}

    type_map: dict[Any, str] = {
        str: "string",
        int: "integer",
        float: "number",
        bool: "boolean",
    }

    for section, mapping in SECTIONS.items():
        section_props: dict[str, Any] = {}
        for key, name in mapping.items():
            info = fields[name]
            annotation = info.annotation
            entry: dict[str, Any] = {}
            if annotation == list[str]:
                entry["type"] = "array"
                entry["items"] = {"type": "string"}
            elif annotation in type_map:
                entry["type"] = type_map[annotation]
            elif annotation == (str | None):
                entry["type"] = ["string", "null"]
            elif get_origin(annotation) is Literal:
                entry["type"] = "string"
                entry["enum"] = list(get_args(annotation))
            if info.description:
                entry["description"] = info.description
            default = Settings.model_fields[name].get_default(call_default_factory=True)
            if default is not None:
                entry["default"] = default
            section_props[key] = entry
        properties[section] = {
            "type": "object",
            "additionalProperties": False,
            "properties": section_props,
        }

    source_props: dict[str, Any] = {}
    for name, info in SourceSpec.model_fields.items():
        key = info.alias or name
        entry = {}
        if info.annotation is bool:
            entry["type"] = "boolean"
        else:
            entry["type"] = "string"
        if info.description:
            entry["description"] = info.description
        source_props[key] = entry

    properties["sources"] = {
        "type": "array",
        "description": Settings.model_fields["sources"].description,
        "items": {
            "type": "object",
            "additionalProperties": False,
            "required": ["slug", "root"],
            "properties": source_props,
        },
    }

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "garage-rag configuration",
        "type": "object",
        "additionalProperties": False,
        "properties": properties,
    }


def setting_names() -> list[str]:
    """Every ``section.key`` the file accepts, in file order."""
    return [f"{section}.{key}" for section, mapping in SECTIONS.items() for key in mapping]


def resolve_setting(name: str) -> tuple[str, str, str]:
    """``"section.key"`` -> ``(section, key, flat field name)``.

    Raises :class:`ConfigError` naming the valid keys, so a typo on the command
    line is caught before anything is written.
    """
    section, dot, key = name.partition(".")
    if not dot or not section or not key:
        raise ConfigError(f"expected SECTION.KEY, got {name!r}; valid keys: {', '.join(setting_names())}")
    mapping = SECTIONS.get(section)
    if mapping is None:
        raise ConfigError(f"unknown section {section!r}; expected one of: {', '.join(SECTIONS)}")
    field = mapping.get(key)
    if field is None:
        raise ConfigError(f"unknown key {key!r} in section {section!r}; expected one of: {', '.join(mapping)}")
    return section, key, field


_TRUE_WORDS = frozenset({"true", "yes", "on", "1"})
_FALSE_WORDS = frozenset({"false", "no", "off", "0"})


def coerce_setting(field: str, raw: str) -> Any:
    """Turn a command-line string into the value ``Settings.<field>`` expects.

    ``bool`` accepts true/false, yes/no, on/off and 1/0; ``int``/``float`` parse
    numerically; ``list[str]`` splits on commas (an empty string is an empty
    list); an optional string becomes ``None`` for ``""``/``none``/``null``.
    Everything else -- plain strings and the ``Literal`` choices -- is passed
    through for pydantic to validate.
    """
    annotation = Settings.model_fields[field].annotation
    text = raw.strip()
    if annotation is bool:
        lowered = text.lower()
        if lowered in _TRUE_WORDS:
            return True
        if lowered in _FALSE_WORDS:
            return False
        raise ConfigError(f"{field}: expected true/false, yes/no, on/off or 1/0, got {raw!r}")
    if annotation is int:
        try:
            return int(text)
        except ValueError:
            raise ConfigError(f"{field}: expected an integer, got {raw!r}") from None
    if annotation is float:
        try:
            return float(text)
        except ValueError:
            raise ConfigError(f"{field}: expected a number, got {raw!r}") from None
    if annotation == list[str]:
        return [item.strip() for item in text.split(",") if item.strip()]
    if annotation == (str | None) and text.lower() in {"", "none", "null"}:
        return None
    return raw


def read_config_document(path: Path) -> dict[str, Any]:
    """The nested JSON document at ``path``, or ``{}`` when the file does not exist.

    Unlike :func:`load_config` this applies no environment override, so what
    :func:`update_config` writes back is what the file already said plus the
    one change -- never an app-managed database URL from the environment.
    """
    path = path.expanduser()
    if not path.is_file():
        return {}
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ConfigError(f"{path} is not valid JSON: {exc}") from exc
    except OSError as exc:
        raise ConfigError(f"cannot read {path}: {exc}") from exc
    if not isinstance(raw, dict):
        raise ConfigError(f"{path} must contain a JSON object")
    return raw


def update_config(path: Path, name: str, raw_value: str) -> tuple[Settings, Any]:
    """Set ``section.key`` to ``raw_value`` in the file at ``path`` and save it.

    The file is read (defaults when absent), the one value coerced and
    substituted, the whole thing validated by round-tripping through
    :class:`Settings`, and then written with :func:`save_config` -- so the
    nested layout, ``$schema`` and key order come out exactly as ``config init``
    would produce them. Returns the saved settings and the coerced value.
    """
    _section, _key, field = resolve_setting(name)
    value = coerce_setting(field, raw_value)
    flat = flatten(read_config_document(path))
    flat[field] = value
    try:
        settings = Settings(**flat)
    except ValidationError as exc:
        raise ConfigError(f"{name}: {exc}") from exc
    save_config(settings, path)
    settings.config_path = path.expanduser()
    return settings, getattr(settings, field)


_settings: Settings | None = None


def get_settings() -> Settings:
    """Process-wide settings singleton."""
    global _settings
    if _settings is None:
        settings = load_config()
        _settings = settings
        return settings
    else:
        return _settings


def set_settings(settings: Settings) -> None:
    """Install a specific configuration. Used by the CLI's --config option."""
    global _settings
    _settings = settings


def reset_settings() -> None:
    global _settings
    _settings = None


def repo_root() -> Path:
    """Path to the repository root (holds the published ``data/`` artifacts)."""
    return Path(__file__).resolve().parents[4]
