load("//bazel:jekyll.bzl", "jekyll_site")

filegroup(
    name = "sources",
    srcs = glob(
        ["**/*"],
        exclude = [
            "BUILD.bazel",
            "BUILD",
            "Gemfile",
            "Gemfile.lock",
            "_config.yml",
        ],
    ),
)

jekyll_site(
    name = "site",
    srcs = [":sources"],
    config = "_config.yml",
    jekyll = "@bundle//bin:jekyll",
    visibility = ["//visibility:public"],
)
